<a href="https://colab.research.google.com/github/Kimgabe/AIFFEL_Online_Quest/blob/main/Quest05(python_final)/%5BAIFFEL_CORE%5D_Python_Main_Quest_%EA%B9%80%EC%8A%B9%EC%88%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📌 Intro.

- 2주간의 파이썬 학습 노드를 최종 점검 하는 퀘스트 입니다.
- 11월 17일 하루동안 일과 시간내에 총 2개의 메인 퀘스트를 풀어야 합니다.
- 각각의 메인퀘스트는 서브 퀘스트를 포함하고 있습니다.

---

1. 메인퀘스트(1) - 은행계좌 생성 및 입/출금등 은행업무를 프로그램화 하는 Account 클래스 만들기
2. 메인퀘스트(2) - Aiffel 캠퍼스의 그루들의 학번 및 퀘스트 수행 점수를 관리하는 Aiffel 클래스 만들기

- 상세 퀘스트트는 각각의 퀘스트 에서 부연설명 하겠습니다.

- 코더 : 김승순 (AIFFEL 온라인 7기, 코어과정)

# 메인퀘스트 (1) - Account 클래스 만들기

## 문제

- **Q1. Account 클래스를 생성하고, 생성자(매직매서드 활용)해 구현하기**
- **Q2. 클래스 변수 생성 : Account 클래스로부터 생성된 객체의 개수를 저장하기**
- **Q3. 클래스 변수 출력 메서드 만들기 : Account 클래스에 생성된 계좌의 계수를 출력하는 get_account_num() 메서드 추가하기**
- **Q4. 입금 메서드(deposit) 만들기 : Account 클래스에 입금을 위한 deposit 메서드 추가. 입금액의 최소단위는 1원입니다.**
- **Q5. 출금 메서드(withdraw) 만들기 : Account 클래스에 출금을 위한 withdraw 메서드 추가. 출금은 계좌의 잔고 이상으로 출금하는 것은 불가합니다.**
- **Q6. 정보출력 메서드(display_info) : Account 인스턴스에 저장된 정보를 출력하는 display_info() 메서드를 추가. 세자리마다 쉼표가 출력되어야 합니다.**
- **Q7. 이자 지급하기 기능 구현 : 입금 횟수가 5회가 될때 잔고를 기준으로 1%의 이자가 잔고에 추가되도록 코드를 변경해야 합니다.**
- **Q8. 여러 객체 생성 : Account 클래스로 부터 3개 이상 인스턴스를 생성하고, 생성된 인스턴스를 리스트에 저장하세요.**
- **Q9. 객체 순환 반복문을 통해 리스트에 있는 객체를 순환하면서 잔고가 100만원 이상인 고객의 정보만 출력하세요.**
- **Q10. 입출금 내역 코드 업데이트 : 입금내역을 출력하는 deposit_history 메서드, 출금내역을 출력하는 withdraw_history 메서드를 추가 하세요.**

---

- 문제의 순서대로 순차적으로 코드를 구현하도록 하겠습니다.
- 전체 클래스 구현에 앞서 어떤 기능을 구현해야 할지 도식화를 해서 큰 그림을 구상한 뒤에 작업을 진행하도록 하겠습니다.


< Account 클래스 전체 구성>
- 전체적인 구조를 머리속에 그리고 시작하기 위해 일단 각각의 메서드의 기능을 정리하였습니다.

![image-3.png](attachment:image-3.png)

### Q1. Account 클래스를 생성하고, 생성자(매직매서드 활용)해 구현하기

< 문제 풀이 과정>
- Account 클래스 를 정의합니다.
- 매직함수를 사용해 생성자를 구현합니다.
- 생성된 생성자(__init__)에서 클래스 활용에 필요한 속성을 정의합니다.
    - account_num : 예금주 이름 저장
    - balance : 초기 잔액을 0원으로 설정
    - bank_name : 'SC은행' 으로 고정
    - account_number : 계좌번호 (랜덤 생성 필요)
- 계좌번호 랜덤 생성 기능 구현

In [ ]:
import random # 계좌번호 랜덤 생성용

# Q1.
class Account:
    # Q1. 생성자 생성
    def __init__(self, account_name):
        self.balance = 0 # 계좌 최초 개설시 0원이므로
        self.balance = 0 # 계좌 최초 개설시 0원이므로
        self.bank_name = 'SC은행' # 은행 이름 고정
        self.account_number = self._generate_account_number()

    # Q1.
    # 랜덤 계좌번호 생성 메서드
    def _generate_account_number(self):
        """
        계좌번호 생성 규칙 : 3자리-2자리-6자리
        random함수의 randint 메서드 활용
        숫자의 범위는 자리수에 따라설정
        구조를 직관적으로 보기 위해 fstring사용 (일반 print문이면 ""와 ,를 섞어야 해서 가독성 떨어짐)
        """
        return f"{random.randint(100,999)}-{random.randint(10,99)}-{random.randint(100000,999999)}"

# 테스트
# 여러명의 고객 객체 생성
test_accounts = [Account("고객1"), Account("고객2"), Account("고객3")]

# 랜덤 계좌정보 출력
account_numbers = [account.account_number for account in test_accounts]
account_numbers

# 인스턴스의 속성 정보 각각 출력
test_accounts_info = [(account.account_number, account.__dict__) for account in test_accounts]
test_accounts_info

[('606-94-335497',
  {'balance': 0, 'bank_name': 'SC은행', 'account_number': '606-94-335497'}),
 ('326-92-754548',
  {'balance': 0, 'bank_name': 'SC은행', 'account_number': '326-92-754548'}),
 ('146-26-178852',
  {'balance': 0, 'bank_name': 'SC은행', 'account_number': '146-26-178852'})]

- 랜덤으로 계좌번호가 이상없이 잘 생성되는걸 볼 수 있고, 계좌잔고도 초기설정 0원이 잘 반영되었습니다.

### Q2. 클래스 변수 생성 : Account 클래스로부터 생성된 객체의 개수를 저장하기

- Account 클래스로부터 생성된 객체의 총 개수를 추적해야 합니다.
- 클래스에 생성된 객체에 대한 정보를 추가하고 저장하기 위한 변수를 추가해야 합니다.
- 생성자를 수정해 새 인스턴스가 생성될때마다 이 변수에 값을 추가해야 합니다.

In [ ]:
import random # 계좌번호 랜덤 생성용

class Account:
    # 계좌 계수 출력위한 변수
    account_count = 0 # 변수 초기화

    # 생성자 생성
    def __init__(self, account_name):
        self.account_name = account_name
        self.balance = 0 # 계좌 최초 개설시 0원이므로
        self.bank_name = 'SC은행' # 은행 이름 고정
        self.account_number = self._generate_account_number()

        # Q2. 새 계좌 생성시 마다 계좌 개수 +1
        Account.account_count += 1


    # 랜덤 계좌번호 생성 메서드
    def _generate_account_number(self):
        """
        계좌번호 생성 규칙 : 3자리-2자리-6자리
        random함수의 randint 메서드 활용
        숫자의 범위는 자리수에 따라설정
        구조를 직관적으로 보기 위해 fstring사용 (일반 print문이면 ""와 ,를 섞어야 해서 가독성 떨어짐)
        """
        return f"{random.randint(100,999)}-{random.randint(10,99)}-{random.randint(100000,999999)}"

# 테스트
# 여러명의 고객 객체 생성
test_accounts = [Account("고객1"), Account("고객2"), Account("고객3")]

# 랜덤 계좌정보 출력
account_numbers = [account.account_number for account in test_accounts]
display(account_numbers)

# 인스턴스의 속성 정보 각각 출력
test_accounts_info = [(account.account_number, account.__dict__) for account in test_accounts]
display(test_accounts_info)

# 생성된 계좌의 개수 출력
print(f" 현재 Account 클래스에 저장된 계좌정보는 총 {Account.account_count} 개 입니다.")

['471-20-782905', '568-27-459762', '165-11-619919']

[('471-20-782905',
  {'account_name': '고객1',
   'balance': 0,
   'bank_name': 'SC은행',
   'account_number': '471-20-782905'}),
 ('568-27-459762',
  {'account_name': '고객2',
   'balance': 0,
   'bank_name': 'SC은행',
   'account_number': '568-27-459762'}),
 ('165-11-619919',
  {'account_name': '고객3',
   'balance': 0,
   'bank_name': 'SC은행',
   'account_number': '165-11-619919'})]

 현재 Account 클래스에 저장된 계좌정보는 총 3 개 입니다.

- 랜덤하게 생성한 3개의 계좌마다 객체의 수가 추가되어 총 3개의 계좌 개수가 정상적으로 출력되는 것을 확인했습니다.

### Q3. 클래스 변수 출력 메서드 만들기 : Account 클래스에 생성된 계좌의 계수를 출력하는 get_account_num() 메서드 추가하기

- Q2. 에서는 클래스에 선언된 변수 자체를 그대로 출력했는데, 이를 출력하는 메서드를 직접 생성하여 출력할 수 있도록 해야 합니다.
- 이를 위해 get_account_num이라는 메서드를 추가해 account_count값을 반환하도록 합니다.
    - 처음에 일반 메서드로 구현을 했는데, 값을 출력하기 위해서는 개별 인스턴스에 접근해서 출력을 해야 해서, 출력 코드가 복잡해집니다.
    - 구글링을 해보니 클래스 메서드로 구현을 하면, 인스턴스에 접근하지 않고 바로 클래스가 보유한 정보를 출력할 수 있다고 합니다.
    - 이를 반영해서 get_account_num를 클래스 메서드로 구현하였습니다.
    - get_account_num 은 데코레이터로서 사용되는 클래스 메서드가 됩니다.(인스턴스 호출없이도 사용 가능)

In [ ]:
import random # 계좌번호 랜덤 생성용

class Account:
    # 계좌 계수 출력위한 변수
    account_count = 0 # 변수 초기화

    # 생성자 생성
    def __init__(self, account_name):
        self.account_name = account_name
        self.balance = 0 # 계좌 최초 개설시 0원이므로
        self.bank_name = 'SC은행' # 은행 이름 고정
        self.account_number = self._generate_account_number()

        # Q2. 새 계좌 생성시 마다 계좌 개수 +1
        Account.account_count += 1


    # 랜덤 계좌번호 생성 메서드
    def _generate_account_number(self):
        """
        계좌번호 생성 규칙 : 3자리-2자리-6자리
        random함수의 randint 메서드 활용
        숫자의 범위는 자리수에 따라설정
        구조를 직관적으로 보기 위해 fstring사용 (일반 print문이면 ""와 ,를 섞어야 해서 가독성 떨어짐)
        """
        return f"{random.randint(100,999)}-{random.randint(10,99)}-{random.randint(100000,999999)}"

    # Q3. 계좌 개수 출력 메서드 추가 -> 추가된 부분
    @classmethod
    def get_account_num(cls):
        return cls.account_count




# 테스트
# 여러명의 고객 객체 생성
test_accounts = [Account("고객1"), Account("고객2"), Account("고객3")]

# 랜덤 계좌정보 출력
account_numbers = [account.account_number for account in test_accounts]
#display(account_numbers)

# 인스턴스의 속성 정보 각각 출력
test_accounts_info = [(account.account_number, account.__dict__) for account in test_accounts]
#display(test_accounts_info)

account_cnt = Account.get_account_num()
print(f" 현재 Account 클래스에 저장된 계좌정보는 총 {account_cnt} 개 입니다.")

 현재 Account 클래스에 저장된 계좌정보는 총 3 개 입니다.

- 일반 메서드로 구현했다가, 출력을 어떻게 할지 몰라서 생성한 여러개의 객체에 직접 접근하면 출력이 되는것을 확인했습니다.
- 하지만 사용이 불편해서 클래스 메서드를 적용해 수정했습니다.
- 결론적으로 이상없이 Q3에 해당하는 'get_account_num' 메서드를 구현해서 Account 클래스가 보유한 계좌의 개수 정보를 출력했습니다.

### Q4. 입금 메서드(deposit) 만들기 : Account 클래스에 입금을 위한 deposit 메서드 추가. 입금액의 최소단위는 1만원입니다.

- 일반 메서드로 입금액을 입력받고, 금액이 1만원 이상인지 검증하여 그 결과를 잔액에 추가해야 합니다.
- 즉, 총 3개의 기능이 구현되어야 합니다.
    - 입금액 입력받는 기능
    - 입금액 검증 하는 기능
    - 입금된 금액을 잔고에 업데이트 하는 기능
- 부가적으로 2가지 출력을 입력하겠습니다.
    - 입금전 잔액 출력
    - 입금 성공 및 실패 여부에 따른 별도의 메시지를 출력

In [ ]:
import random # 계좌번호 랜덤 생성용

class Account:
    # 계좌 계수 출력위한 변수
    account_count = 0 # 변수 초기화

    # 생성자 생성
    def __init__(self, account_name):
        self.account_name = account_name
        self.balance = 0 # 계좌 최초 개설시 0원이므로
        self.bank_name = 'SC은행' # 은행 이름 고정
        self.account_number = self._generate_account_number()

        # 새 계좌 생성시 마다 계좌 개수 +1
        Account.account_count += 1


    # 랜덤 계좌번호 생성 메서드
    def _generate_account_number(self):
        """
        계좌번호 생성 규칙 : 3자리-2자리-6자리
        random함수의 randint 메서드 활용
        숫자의 범위는 자리수에 따라설정
        구조를 직관적으로 보기 위해 fstring사용 (일반 print문이면 ""와 ,를 섞어야 해서 가독성 떨어짐)
        """
        return f"{random.randint(100,999)}-{random.randint(10,99)}-{random.randint(100000,999999)}"

    # 계좌 개수 출력 메서드 추가
    @classmethod
    def get_account_num(cls):
        return cls.account_count

    # Q4. 입금 메서드 추가
    def deposit(self, amount):
        # 입금전 현재 잔액 정보 출력
        print("입금 전 잔액:", "{:,}원".format(self.balance)) # 천단위 쉼표 기능 구현(Q6 대비)

        # 최소 입금액 기준 충족 여부 판단
        if amount >= 1:
            self.balance += amount # 잔고에 입금액 추가
            # 결과 출력
            print(f"입금 성공! - 현재 잔액은 {self.balance:,}원 입니다.") # 천단위 쉼표 기능 구현(Q6 대비)
        # 최소 입금액 미충족시 문구 출력
        else:
            print(f"입금 실패! - 입금 시도액: {amount}원. 최소 입금액은 1원입니다. 재입금을 시도해주세요!")



# 테스트
customer1 = Account("김승순") # 신규고객 생성
customer2 = Account("김아이펠") # 신규고객 생성

# 고객 1 20,000원 입금 시도
customer1.deposit(20000)

# 고객 2 0원 입금 시도
customer2.deposit(0)

입금 전 잔액: 0원
입금 성공! - 현재 잔액은 20,000원 입니다.
입금 전 잔액: 0원
입금 실패! - 입금 시도액: 0원. 최소 입금액은 1원입니다. 재입금을 시도해주세요!

- 처음 의도한대로 입금전 잔액을 출력하였으며, 입금액에 따라 성공 및 실패에 따른 각각의 메시지를 출력하도록 했습니다.
- 금액에 천단위로 쉼표도 Q6에 구현하여야 하는 부분인데 지속적으로 사용하기 위해 미리 입력하였습니다.

## Q5. 출금 메서드(withdraw) 만들기 : Account 클래스에 출금을 위한 withdraw 메서드 추가. 출금은 계좌의 잔고 이상으로 출금하는 것은 불가합니다.

- 출금 가능 여부를 검증하는 기능이 우선적으로 작동해야 합니다.
- 검증된 금액을 출금하면, 해당 내용을 잔액에 업데이트(차감)하도록 구현합니다.
- 그 외 출력문 방식은 deposit과 동일한 방식으로 작성합니다.

In [ ]:
import random # 계좌번호 랜덤 생성용

class Account:
    # 계좌 계수 출력위한 변수
    account_count = 0 # 변수 초기화

    # 생성자 생성
    def __init__(self, account_name):
        self.account_name = account_name
        self.balance = 0 # 계좌 최초 개설시 0원이므로
        self.bank_name = 'SC은행' # 은행 이름 고정
        self.account_number = self._generate_account_number()

        # 새 계좌 생성시 마다 계좌 개수 +1
        Account.account_count += 1


    # 랜덤 계좌번호 생성 메서드
    def _generate_account_number(self):
        """
        계좌번호 생성 규칙 : 3자리-2자리-6자리
        random함수의 randint 메서드 활용
        숫자의 범위는 자리수에 따라설정
        구조를 직관적으로 보기 위해 fstring사용 (일반 print문이면 ""와 ,를 섞어야 해서 가독성 떨어짐)
        """
        return f"{random.randint(100,999)}-{random.randint(10,99)}-{random.randint(100000,999999)}"

    # 계좌 개수 출력 메서드 추가
    @classmethod
    def get_account_num(cls):
        return cls.account_count

    # Q4. 입금 메서드 추가
    def deposit(self, amount):
        # 입금전 현재 잔액 정보 출력
        print("입금 전 잔액:", "{:,}원".format(self.balance)) # 천단위 쉼표 기능 구현(Q6 대비)

        # 최소 입금액 기준 충족 여부 판단
        if amount >= 1:
            self.balance += amount # 잔고에 입금액 추가
            # 결과 출력
            print(f"입금 성공! - 현재 잔액은 {self.balance:,}원 입니다.") # 천단위 쉼표 기능 구현(Q6 대비)
        # 최소 입금액 미충족시 문구 출력
        else:
            print(f"입금 실패! - 입금 시도액: {amount}원. 최소 입금액은 1원입니다. 재입금을 시도해주세요!")


    # Q5. 출금 메서드 추가
    def withdraw(self, amount):
        # 현재 잔고 출력
        print("현재 잔고 :", "{:,}원".format(self.balance))

        # 출고 요청 금액에 대한 출금 여부 검증
        if amount <= self.balance:
            self.balance -= amount # 출금요청금액을 잔고에 반영(차감)
            print(f"출금 성공! - 현재 잔액은 {self.balance:,}원 입니다.")
        else:
            print(f"출금 실패! - 출금 시도액: {amount}원. 잔액이 부족합니다.")




# 테스트
customer1 = Account("김승순") # 신규고객 생성
customer2 = Account("김아이펠") # 신규고객 생성

# 고객 1 20,000원 입금
customer1.deposit(20000)

# 고객 1 10,000원 출금 시도 - 성공 메시지 출력
customer1.withdraw(10000)

# 고객 2 50000원 입금
customer2.deposit(50000)

# 고객 2 60000원 출금 시도 - 실패 메시지 출력
customer2.withdraw(60000)

입금 전 잔액: 0원
입금 성공! - 현재 잔액은 20,000원 입니다.
현재 잔고 : 20,000원
출금 성공! - 현재 잔액은 10,000원 입니다.
입금 전 잔액: 0원
입금 성공! - 현재 잔액은 50,000원 입니다.
현재 잔고 : 50,000원
출금 실패! - 출금 시도액: 60000원. 잔액이 부족합니다.

- 의도했던데로 출금전 잔고를 출력하고, 그 금액에 대한 시도에 따른 각각의 결과를 올바르게 출력함을 확인했습니다.

## Q6. 정보출력 메서드(display_info) : Account 인스턴스에 저장된 정보를 출력하는 display_info() 메서드를 추가. 세자리마다 쉼표가 출력되어야 합니다.

- 계좌정보에 은행명, 예금주, 계좌번호, 잔액이 모두 포함되어야 합니다.(위에서 사용할 코드 구현 완료)
- 잔액은 천원단위마다 쉼표가 입력되어야 합니다.(위에서 사용할 코드 구현 완료)
- 정보출력 메서드(display_info)를 추가하고 위의 2가지 기능을 추가합니다.
    - 인스턴스 변수에서 출력할 정보들 가져오기
    - 잔액 출력시 천원단위별 쉼표 추가하여 출력하기

In [ ]:
import random # 계좌번호 랜덤 생성용

class Account:
    # 계좌 계수 출력위한 변수
    account_count = 0 # 변수 초기화

    # 생성자 생성
    def __init__(self, account_name):
        self.account_name = account_name
        self.balance = 0 # 계좌 최초 개설시 0원이므로
        self.bank_name = 'SC은행' # 은행 이름 고정
        self.account_number = self._generate_account_number()

        # 새 계좌 생성시 마다 계좌 개수 +1
        Account.account_count += 1


    # 랜덤 계좌번호 생성 메서드
    def _generate_account_number(self):
        """
        계좌번호 생성 규칙 : 3자리-2자리-6자리
        random함수의 randint 메서드 활용
        숫자의 범위는 자리수에 따라설정
        구조를 직관적으로 보기 위해 fstring사용 (일반 print문이면 ""와 ,를 섞어야 해서 가독성 떨어짐)
        """
        return f"{random.randint(100,999)}-{random.randint(10,99)}-{random.randint(100000,999999)}"

    # 계좌 개수 출력 메서드 추가
    @classmethod
    def get_account_num(cls):
        return cls.account_count

    # Q4. 입금 메서드 추가
    def deposit(self, amount):
        # 입금전 현재 잔액 정보 출력
        print("입금 전 잔액:", "{:,}원".format(self.balance)) # 천단위 쉼표 기능 구현(Q6 대비)

        # 최소 입금액 기준 충족 여부 판단
        if amount >= 1:
            self.balance += amount # 잔고에 입금액 추가
            # 결과 출력
            print(f"입금 성공! - 현재 잔액은 {self.balance:,}원 입니다.") # 천단위 쉼표 기능 구현(Q6 대비)
        # 최소 입금액 미충족시 문구 출력
        else:
            print(f"입금 실패! - 입금 시도액: {amount}원. 최소 입금액은 1원입니다. 재입금을 시도해주세요!")


    # Q5. 출금 메서드 추가
    def withdraw(self, amount):
        # 현재 잔고 출력
        print("현재 잔고 :", "{:,}원".format(self.balance))

        # 출고 요청 금액에 대한 출금 여부 검증
        if amount <= self.balance:
            self.balance -= amount # 출금요청금액을 잔고에 반영(차감)
            print(f"출금 성공! - 현재 잔액은 {self.balance:,}원 입니다.")
        else:
            print(f"출금 실패! - 출금 시도액: {amount}원. 잔액이 부족합니다.")


    # Q6. 정보출력 메서드 구현하기
    def display_info(self):
        # 각각의 정보를 출력하는 print문 작성
        print(f"은행 이름: {self.bank_name}")
        print(f"예금주: {self.account_name}")
        print(f"계좌번호: {self.account_number}")
        print(f"잔액: {self.balance:,}원")



# 테스트
customer1 = Account("김승순") # 신규고객 생성


# 고객 1 20,000원 입금
customer1.deposit(20000)
customer1.display_info()

입금 전 잔액: 0원
입금 성공! - 현재 잔액은 20,000원 입니다.
은행 이름: SC은행
예금주: 김승순
계좌번호: 281-30-744879
잔액: 20,000원

- 이전 문제에서 구현한 코드들과 인스턴스 정보들을 가져와 바로 출력하게 함으로써 display_info 메서드를 성공적으로 구현했습니다.

## Q7. 이자 지급하기 기능 구현 : 입금 횟수가 5회가 될때 잔고를 기준으로 1%의 이자가 잔고에 추가되도록 코드를 변경해야 합니다.

- 처음 클래스 구조를 그릴때 구상한 바와 같이 deposit 메서드 아래 이자를 지급하는 기능을 구현했습니다.
- 기존 메서드 하위에 기능을 구성한 이유는 기능의 구분을 명확하게 하기 위함 입니다.
- 입금이란 액션이 일어날때 발생하는 추가적인 액션이기 때문에 deposit이 발생하는 횟수에 따라 작동하도록 구현했습니다.
- 이 경우 매 입금마다 이자 지급 조건을 검토하므로 별도로 기능을 불러와서 사용할 필요 없이 자동으로 작동하도록 할 수 있습니다.

---

- 기능 구현을 위해 필요한 사항은 다음과 같습니다.
    - 입금 횟수 추적 : deposit이 실행될때마다 입금 횟수를 추적하는 인스턴스 변수가 추가되어야 합니다.
    - 이자 지급을 위한 로직 추가 : 입금횟수 5회마다 잔액을 조회하고, 그 잔액(5회차 입금액 포함)의 1%를 추가로 입금해야 합니다.
    - 지급한 이자를 잔고에 업데이트 해야 합니다.
- 각 기능에서 필요한 print 문도 적절하게 포함하여 추가하겠습니다.
    - 이자 지급 조건 충족 여부
    - 이자 금액(소수점2자리)
- 부가적으로 이자로 인해 소수점이 늘어나므로, 이후의 금액 출력관련 부분은 소수점 2자리까지만 출력하는것으로 일괄 수정했습니다.

In [ ]:
import random # 계좌번호 랜덤 생성용

class Account:
    # 계좌 계수 출력위한 변수
    account_count = 0 # 변수 초기화

    # 생성자 생성
    def __init__(self, account_name):
        self.account_name = account_name
        self.balance = 0 # 계좌 최초 개설시 0원이므로
        self.bank_name = 'SC은행' # 은행 이름 고정
        self.account_number = self._generate_account_number()

        # 새 계좌 생성시 마다 계좌 개수 +1
        Account.account_count += 1

        # Q7에서 추가된 코드
        self.deposit_count = 0 # 입금 횟수 추적 위한 변수


    # 랜덤 계좌번호 생성 메서드
    def _generate_account_number(self):
        """
        계좌번호 생성 규칙 : 3자리-2자리-6자리
        random함수의 randint 메서드 활용
        숫자의 범위는 자리수에 따라설정
        구조를 직관적으로 보기 위해 fstring사용 (일반 print문이면 ""와 ,를 섞어야 해서 가독성 떨어짐)
        """
        return f"{random.randint(100,999)}-{random.randint(10,99)}-{random.randint(100000,999999)}"

    # 계좌 개수 출력 메서드 추가
    @classmethod
    def get_account_num(cls):
        return cls.account_count

    # Q4. 입금 메서드 추가
    # Q7. 이자지급 메서드를 deposit의 하위 메서드로 추가
    def deposit(self, amount):
        # 입금전 현재 잔액 정보 출력
        print("입금 전 잔액:", "{:,}원".format(self.balance)) # 천단위 쉼표 기능 구현(Q6 대비)

        # 최소 입금액 기준 충족 여부 판단
        if amount >= 1:
            self.balance += amount # 잔고에 입금액 추가
            self.deposit_count += 1 # 입금횟수 증가
            # 결과 출력
            print(f"입금 성공! - 현재 잔액은 {self.balance:,.2f}원 입니다.") # 천단위 쉼표 기능 구현(Q6 대비)


            # Q7. 입금 5회당 이자 지급 기능 추가하는 코드
            if self.deposit_count % 5 == 0: # 5회당 이므로 5로 나누어 나머지가 0이되어야 함
                interest = self.balance * 0.01 # 잔고(balance)를 불러오고 해당 금액의 1% 이자로 계산
                self.balance += interest # 이자 지급 및 반영
                print(f"누적 입금 시도가 {self.deposit_count}회입니다! 내부정책에 따라 현재 잔고의 1%를 이자로 지급합니다.")
                print(f"추가 이자 지급: {interest:,.2f}원 - 새로운 잔액: {self.balance:,.2f}원")

        # 최소 입금액 미충족시 문구 출력
        else:
            print(f"입금 실패! - 입금 시도액: {amount}원. 최소 입금액은 1원입니다. 재입금을 시도해주세요!")


    # Q5. 출금 메서드 추가
    def withdraw(self, amount):
        # 현재 잔고 출력
        print("현재 잔고 :", "{:,}원".format(self.balance))

        # 출고 요청 금액에 대한 출금 여부 검증
        if amount <= self.balance:
            self.balance -= amount # 출금요청금액을 잔고에 반영(차감)
            print(f"출금 성공! - 현재 잔액은 {self.balance:,.2f}원 입니다.")
        else:
            print(f"출금 실패! - 출금 시도액: {amount}원. 잔액이 부족합니다.")


    # Q6. 정보출력 메서드 구현하기
    def display_info(self):
        # 각각의 정보를 출력하는 print문 작성
        print(f"은행 이름: {self.bank_name}")
        print(f"예금주: {self.account_name}")
        print(f"계좌번호: {self.account_number}")
        print(f"잔액: {self.balance:,.2f}원")



# 테스트
customer1 = Account("김승순") # 신규고객 생성

# 5회 입금 시도
for _ in range(5):
    customer1.deposit(10000) # 매번 만원씩 입금

# 계좌 정보 출력
customer1.display_info()

입금 전 잔액: 0원
입금 성공! - 현재 잔액은 10,000.00원 입니다.
입금 전 잔액: 10,000원
입금 성공! - 현재 잔액은 20,000.00원 입니다.
입금 전 잔액: 20,000원
입금 성공! - 현재 잔액은 30,000.00원 입니다.
입금 전 잔액: 30,000원
입금 성공! - 현재 잔액은 40,000.00원 입니다.
입금 전 잔액: 40,000원
입금 성공! - 현재 잔액은 50,000.00원 입니다.
누적 입금 시도가 5회입니다! 내부정책에 따라 현재 잔고의 1%를 이자로 지급합니다.
추가 이자 지급: 500.00원 - 새로운 잔액: 50,500.00원
은행 이름: SC은행
예금주: 김승순
계좌번호: 772-62-970176
잔액: 50,500.00원

- 의도한대로 5회차의 누적 입금액(잔고)에 따라 이자가 지급됨을 확인했고, 안내문구 및 결과 문구, 금액에 대한 소수점 2번째자리까지의 반영 등이 모두 의도한대로 반영되었습니다.

## Q8. 여러 객체 생성 : Account 클래스로 부터 3개 이상 인스턴스를 생성하고, 생성된 인스턴스를 리스트에 저장하세요.

- Account 클래스를 사용해 여러명의 고객에 대한 인스턴스를 생성합니다.
- 생성된 고객들의 계좌(인스턴스)를 리스트에 저장합니다.

In [ ]:
# 여러 계좌 인스턴스 생성 및 리스트에 저장
accounts_list = [
    Account("김승순"),
    Account("김아이펠"),
    Account("김하사비스")
]

# 생성된 계좌 인스턴스 정보 출력 테스트
for account in accounts_list:
    account.display_info()
    print("---") # 가독성 위해 경계선 출력 추가

은행 이름: SC은행
예금주: 김승순
계좌번호: 517-93-398160
잔액: 0.00원
---
은행 이름: SC은행
예금주: 김아이펠
계좌번호: 888-60-817673
잔액: 0.00원
---
은행 이름: SC은행
예금주: 김하사비스
계좌번호: 806-84-821350
잔액: 0.00원
---

- 각각의 고객이 서로 다른 랜덤한 계좌번호와 초기 잔고(0원)을 가지고 입력되어 있음을 확인할 수 있습니다.

## Q9. 객체 순환 반복문을 통해 리스트에 있는 객체를 순환하면서 잔고가 100만원 이상인 고객의 정보만 출력하세요.

- Q8에서 생성한 고객 인스턴스중에 100만원 이상인 계좌 정보만 출력해야 합니다.
- 현재는 모두 잔고가0원이므로 여러 결과를 보기 위해 100만원을 한 고객의 계좌에 입금해 두고 작업을 시작하겠습니다.
- 이후 리스트에서 조건문을 통해 accounts_list에서 잔고가 100만원 이상인 계좌만 출력하는 코드를 작성해서 확인해보겠습니다.

In [ ]:
# 임의의 금액을 각 계좌에 입금하여 잔고 설정
accounts_list[0].deposit(500000)  # 김승순 계좌에 500,000원 입금
accounts_list[1].deposit(1000000) # 김아이펠 계좌에 1,000,000원 입금
accounts_list[2].deposit(1500000) # 김사하비스 계좌에 1,500,000원 입금

# 잔고가 100만원 이상인 계좌 정보만 출력
for account in accounts_list:
    if account.balance >= 1000000:  # 잔고 100만원 이상 확인
        account.display_info()
        print("---")

입금 전 잔액: 0원
입금 성공! - 현재 잔액은 500,000.00원 입니다.
입금 전 잔액: 0원
입금 성공! - 현재 잔액은 1,000,000.00원 입니다.
입금 전 잔액: 0원
입금 성공! - 현재 잔액은 1,500,000.00원 입니다.
은행 이름: SC은행
예금주: 김아이펠
계좌번호: 888-60-817673
잔액: 1,000,000.00원
---
은행 이름: SC은행
예금주: 김하사비스
계좌번호: 806-84-821350
잔액: 1,500,000.00원
---

- 각각의 입금액이 반영된 것을 확인할 수 있었고, 잔고가 100만원 이상인 '김사하사비스' 고객에 대한 정보만 출력된 것을 확인할 수 있습니다.
- 2명도 출력되는지 확인하기 위해 김아이펠에게 100만원을 더 입금 시키고 재시도 해보겠습니다.

In [ ]:
accounts_list[1].deposit(1000000) # 김아이펠 계좌에 1,000,000원 입금

# 잔고가 100만원 이상인 계좌 정보만 출력
for account in accounts_list:
    if account.balance >= 1000000:  # 잔고 100만원 이상 확인
        account.display_info()
        print("---")

입금 전 잔액: 1,000,000원
입금 성공! - 현재 잔액은 2,000,000.00원 입니다.
은행 이름: SC은행
예금주: 김아이펠
계좌번호: 888-60-817673
잔액: 2,000,000.00원
---
은행 이름: SC은행
예금주: 김하사비스
계좌번호: 806-84-821350
잔액: 1,500,000.00원
---

- 처음에는 김사하비스 고객만 출력되던게 추가된 누적 금이 100만원이상인 김아이펠 고객까지 출력됨을 확인할 수 있었습니다.
- 이로서 Q9에 대한 요구사항을 모두 충족하였음을 확인했습니다.

## Q10. 입출금 내역 코드 업데이트 : 입금내역을 출력하는 deposit_history 메서드, 출금내역을 출력하는 withdraw_history 메서드를 추가 하세요.

- 입출금 내역을 기록하였다가 출력하는 메서드를 각각 만들어야 합니다.
- 이를 위해 입/출금시 발생하는 각 거래 내역을 저장할 변수를 생성자에 추가해야 합니다.
- 입/출금시마다 발생하는 정보를
- 또한 해당 정보를 불러와서

In [ ]:
import random # 계좌번호 랜덤 생성용

class Account:
    # 계좌 계수 출력위한 변수
    account_count = 0 # 변수 초기화

    # 생성자 생성
    def __init__(self, account_name):
        self.account_name = account_name
        self.balance = 0 # 계좌 최초 개설시 0원이므로
        self.bank_name = 'SC은행' # 은행 이름 고정
        self.account_number = self._generate_account_number()

        # 새 계좌 생성시 마다 계좌 개수 +1
        Account.account_count += 1

        # Q7에서 추가된 코드
        self.deposit_count = 0 # 입금 횟수 추적 위한 변수

        # Q10. 에서 추가된 코드
        self.deposit_history_list = []  # 입금 내역 저장을 위한 리스트
        self.withdraw_history_list = []  # 출금 내역 저장을 위한 리스트


    # 랜덤 계좌번호 생성 메서드
    def _generate_account_number(self):
        """
        계좌번호 생성 규칙 : 3자리-2자리-6자리
        random함수의 randint 메서드 활용
        숫자의 범위는 자리수에 따라설정
        구조를 직관적으로 보기 위해 fstring사용 (일반 print문이면 ""와 ,를 섞어야 해서 가독성 떨어짐)
        """
        return f"{random.randint(100,999)}-{random.randint(10,99)}-{random.randint(100000,999999)}"

    # 계좌 개수 출력 메서드 추가
    @classmethod
    def get_account_num(cls):
        return cls.account_count

    # Q4. 입금 메서드 추가
    # Q7. 이자지급 메서드를 deposit의 하위 메서드로 추가
    def deposit(self, amount):
        # 입금전 현재 잔액 정보 출력
        print("입금 전 잔액:", "{:,}원".format(self.balance)) # 천단위 쉼표 기능 구현(Q6 대비)

        # 최소 입금액 기준 충족 여부 판단
        if amount >= 1:
            self.balance += amount # 잔고에 입금액 추가
            self.deposit_count += 1 # 입금횟수 증가
            self.deposit_history_list.append(amount)  # 입금 내역에 추가
            # 결과 출력
            print(f"입금 성공! - 현재 잔액은 {self.balance:,.2f}원 입니다.") # 천단위 쉼표 기능 구현(Q6 대비)


            # Q7. 입금 5회당 이자 지급 기능 추가하는 코드
            if self.deposit_count % 5 == 0: # 5회당 이므로 5로 나누어 나머지가 0이되어야 함
                interest = self.balance * 0.01 # 잔고(balance)를 불러오고 해당 금액의 1% 이자로 계산
                self.balance += interest # 이자 지급 및 반영
                print(f"누적 입금 시도가 {self.deposit_count}회입니다! 내부정책에 따라 현재 잔고의 1%를 이자로 지급합니다.")
                print(f"추가 이자 지급: {interest:,.2f}원 - 새로운 잔액: {self.balance:,.2f}원")

        # 최소 입금액 미충족시 문구 출력
        else:
            print(f"입금 실패! - 입금 시도액: {amount}원. 최소 입금액은 1원입니다. 재입금을 시도해주세요!")


    # Q5. 출금 메서드 추가
    def withdraw(self, amount):
        # 현재 잔고 출력
        print("현재 잔고 :", "{:,}원".format(self.balance))

        # 출고 요청 금액에 대한 출금 여부 검증
        if amount <= self.balance:
            self.balance -= amount # 출금요청금액을 잔고에 반영(차감)
            # Q10. 출금 내역 history로 저장
            self.withdraw_history_list.append(amount)
            print(f"출금 성공! - 현재 잔액은 {self.balance:,.2f}원 입니다.")
        else:
            print(f"출금 실패! - 출금 시도액: {amount}원. 잔액이 부족합니다.")


    # Q6. 정보출력 메서드 구현하기
    def display_info(self):
        # 각각의 정보를 출력하는 print문 작성
        print(f"은행 이름: {self.bank_name}")
        print(f"예금주: {self.account_name}")
        print(f"계좌번호: {self.account_number}")
        print(f"잔액: {self.balance:,.2f}원")


    # Q10. 입금 내역 메서드 추가
    def deposit_history(self):
        for deposit in self.deposit_history_list: # 생성자에 있는 deposit_history_list를 iteration하며 정보 조회
            print(f" - {deposit:,.2f}원 입금") # 각 입금 기록을 출력
        if not self.deposit_history_list: # 아직 기록이 없는 경우
            print("입금 내역이 없습니다.")

    # Q10. 출금 내역 메서드 추가
    def withdraw_history(self):
        for withdraw in self.withdraw_history_list: # 생성자에 있는 withdraw_history_list를 iteration하며 정보 조회
            print(f" - {withdraw:,.2f}원 출력") # 각 출금 기록을 출력
        if not self.withdraw_history_list: # 아직 기록이 없는 경우
            print("출금 내역이 없습니다.")


# 테스트
customer1 = Account("김승순")
customer1.deposit(10000)  # 입금
customer1.withdraw(5000)  # 출금
customer1.deposit(20000)  # 입금

# 입금 및 출금 내역 출력
customer1.deposit_history()
customer1.withdraw_history()

입금 전 잔액: 0원
입금 성공! - 현재 잔액은 10,000.00원 입니다.
현재 잔고 : 10,000원
출금 성공! - 현재 잔액은 5,000.00원 입니다.
입금 전 잔액: 5,000원
입금 성공! - 현재 잔액은 25,000.00원 입니다.
 - 10,000.00원 입금
 - 20,000.00원 입금
 - 5,000.00원 출력

- 처음에 의도 했던 대로 각각의 입출력 내용이 리스트에 저장되어있다가 출력되고 있음을 확인할 수 있습니다.

# 메인퀘스트 (2) - Aiffel 클래스 만들기

- AIFFEL은 그루들에게 학번을 부여하고 퀘스트 점수를 관리하고 있습니다. 이제부터 학번과 점수를 관리할 수 있는 Aiffel이라는 클래스를 만들도록 하겠습니다.
- 이니셜라이저는 아래 4개의 인자를 받습니다.
    - 이름, 입학연도, 기수, 과정명
- 학번은 7자리로 이뤄져 있으며 학번 생성 규칙은 아래와 같습니다.
    - YYNNCXX
    - YY : 연도 마지막 두자리(ex. 2023년의 YY는 23)
    - NN : 기수 (온라인 7기는 29기입니다.)
    - C : 과정 종류(리서치 = 1, 코어=2)
    - XX : 가나다순 번호

---

## 전체 문제

- **Q1. 코어 명단(딕셔너리)를 입력받아 학번을 부여하는 초기화 메서드를 작성해 보세요**
    - {강영현: 0, 김경민:0, 김민기: 0, 김승순: 0, 김양희: 0, 김영신:0, 오우진: 0, 윤혜윤: 0, 이상원: 0, 이선재: 0, 이슬: 0, 이승환: 0, 전민규: 0, 조보겸: 0, 조수민: 0, 최강훈: 0, 한현종: 0,홍채림: 0}
- **Q2. Aiffel 클래스로부터 생성된 학번의 개수를 출력하는 get_id_num() 메서드를 추가하세요.**
- **Q3. Aiffel 클래스에 퀘스트 점수 입력을 위한 score 메서드를 추가하세요. 점수는 +1점 부터 +3점까지만 가능합니다.**
- **Q4. Aiffel 클래스에 퀘스트 점수 차감을 위한 penalty 메서드를 추가하세요. penalty로 인한 잔여 점수는 음수가 가능합니다.**
- **Q5. Aiffel 인스턴스에 저장된 정보를 출력하는 display_info() 메서드를 추가하세요. 해당 메서드를 호출하면 이름, 학번, 과정종류, 퀘스트 점수 총점, 퀘스트 입력 총점, 퀘스트 penalty 총합이 새로운 코어명단(csv파일)로 출력되어야합니다.**
- **Q6. 중도포기자 관리를 위해 그루정보를 삭제하는 메서드를 추가해보세요. 해당 메서드를 호출하면 명단이 갱신되어야 합니다. 현재 명단에서 김경민, 김영신 님을 삭제한 후 갱신된 명단을 출력하세요.**
- **Q7. Aiffel 클래스를 상속하여, 그루 명단을 바탕으로 2인, 3인, 4인으로 랜덤 그룹핑을 해주는 메서드가 추가된 Aiffel_Group 클래스를 만들어 보세요. 그룹이름은 총 8개입니다. (상생, 신뢰, 열정, 이끔, 성장, 가치, 공유, 확산)**
- **Q8. Aiffel 클래스를 상속하여, 그루 명단을 바탕으로 "힌튼", "응", "하사비스" 세개의 길드로 그루들을 랜덤 그룹핑 해주는 Aiffel_Guild 클래스를 만들어 보세요.**
- **Q9. Aiffel_Guild 클래스에 길드별 점수를 입력하고 차감하는 guild_score 메서드를 추가해보세요. guild_score 메서드는 길드 이름과 점수를 인자로 받고 길드별 스코어를 출력합니다. guild_score 메서드ㅏ로 점수가 입력되거나 차감되면, Aiffel 클래스에서 구현된 개별 그루의 score도 소속 길드에서 추가되거나 차감된 점수에 따라 별도로 증감되어야 합니다.**
    - ex) 모든 길드의 점수가 현재 0점이고, 김양희, 조수민, 조보겸 그루의 개별 점수가 각각 2,3,1이며, 박영수, 심지안 그루는 힌튼 길드, 박근수 그루는 응 길드 라고 했을 때, 힌튼 길드가 -1점, 응길드가 +1점을 받았다면 길드점수는 힌튼 길드 -1, 응 길드 +1, 하사비스 길드 +0이 되어야 하고 김양희, 조보겸 그루는 각각 1점과 0점, 조수민 그루는 4점이 되어야 합니다.
- **10. Aiffel_Group 클래스에 group2guild_score 메서드를 추가하세요. group2guild_score 메서드는 아래와 같이 작동해야 합니다.**
    - 랜덤으로 그룹핑된 그루들이 소속된 그룹의 이름으로 점수를 받게 되면, 각자 소속된 길드의 점수로 연동되어 계산되게 합니다.
    - ex) 이선재(Q8에서 응 길드원으로 랜덤 배치되었다 가정), 강영현(Q8에서 힌튼 길드원으로 랜덤 배치되었다 가정), 한현종(Q8에서 하사비스 길드원으로 랜덤 배치되었다 가정) 3명이 "상상" 그룹으로 그룹핑 되었을 때,상생 그룹이 +2점을 받으면 "응"길드와 "힌튼길드"와 "하사비스" 길드의 스코어는 각각 +2점이 되어야 합니다.
- **11. Aiffel_Group 클래스와 Aiffel_Guild클래스가 Aiffel 클래스의 display_info() 메서드를 아래와 같이 오버라이딩 하도록 합니다.**
    - 기존 명단에 길드별 스코어 총합이 보이도록 명단을 출력하도록 display_info()를 오버라이딩 합니다.
    
    
- 단순 클래스 생성을 넘어서, 클래스간상속, 오버라이딩등 좀 더 심화된 문제가 주어졌습니다.
- 문제 풀이에 앞서 각 클래스와, 메서드간 구조에 대해 이해를 하고 시작해야 할 것 같습니다.

![image-2.png](attachment:image-2.png)

### **Q1. 코어 명단(딕셔너리)를 입력받아 학번을 부여하는 초기화 메서드를 작성해 보세요**

- 일단 Aiffel클래스와 인스턴스를 생성해야 합니다.
- 이후 사전에 지정한 코어명단 딕셔너리를 입력받아 정해진 규칙에 따라 학번을 생성해야 합니다.
- 학번의 경우 가나다 규칙을 제외하고는 모두 같은 값이므로 일괄입력받아 적용하도록 하겠습니다.
- 그 외 이름의 경우 이미 적용이 되어있긴하나, 차후 추가 사용 가능성을 고려해 가다다순 정렬을 적용하도록 하겠습니다.
- 이 로직이 적용된 학번 생성 기능을 generate_student_id 라는 메서드로 추가하겠습니다.

In [ ]:
class Aiffel:
    # 생성된 학번의 총 개수
    total_id_count = 0  # 초기화

    def __init__(self, name, admission_year="2023", term=29, course_type="코어"):
        self.name = name  # 학생의 이름
        self.admission_year = admission_year  # 입학 연도
        self.term = term  # 기수
        self.course_type = course_type  # 과정 종류
        self.student_id = self.generate_student_id()  # 학번 생성 메서드 호출
        Aiffel.total_id_count += 1  # 학번이 생성될 때마다 카운트 증가

    def generate_student_id(self):
        year = self.admission_year[-2:]  # 입학 연도의 마지막 두 자리
        course_type_num = '2' if self.course_type == "코어" else '1'  # 과정 종류에 따른 숫자 할당
        student_number = str(Aiffel.total_id_count + 1).zfill(2)  # 학번의 순서를 나타내는 두 자리 숫자
        student_id = f"{year}{str(self.term).zfill(2)}{course_type_num}{student_number}"  # 학번 조합
        return student_id  # 생성된 학번 반환

# 코어 명단 dict
core_members =  {'강영현': 0, '김경민': 0, '김민기': 0, '김승순': 0, '김양희': 0, '김영신': 0,
                 '오우진': 0, '윤혜윤': 0, '이상원': 0, '이선재': 0, '이슬': 0, '이승환': 0, '전민규': 0,
                 '조보겸': 0, '조수민': 0, '최강훈': 0, '한현종': 0, '홍채림': 0}

# 코어 명단을 바탕으로 Aiffel 인스턴스 생성
members_instances = {} # 코어 명단 dict를 바탕으로 Aiffel 클래스의 인스턴스를 생성용 dict

# 각 학생의 이름을 사용하여 Aiffel 클래스의 인스턴스를 생성
# Aiffel 클래스의 생성자에 정의된 기본값(연도, 기수, 과정 종류) 적용
for name in core_members.keys():
    members_instances[name] = Aiffel(name)

# 생성된 인스턴스(그루)의 학번 확인
for name, instance in members_instances.items():
    print(f"이름: {name}, 학번: {instance.student_id}")

이름: 강영현, 학번: 2329201
이름: 김경민, 학번: 2329202
이름: 김민기, 학번: 2329203
이름: 김승순, 학번: 2329204
이름: 김양희, 학번: 2329205
이름: 김영신, 학번: 2329206
이름: 오우진, 학번: 2329207
이름: 윤혜윤, 학번: 2329208
이름: 이상원, 학번: 2329209
이름: 이선재, 학번: 2329210
이름: 이슬, 학번: 2329211
이름: 이승환, 학번: 2329212
이름: 전민규, 학번: 2329213
이름: 조보겸, 학번: 2329214
이름: 조수민, 학번: 2329215
이름: 최강훈, 학번: 2329216
이름: 한현종, 학번: 2329217
이름: 홍채림, 학번: 2329218

## **Q2. Aiffel 클래스로부터 생성된 학번의 개수를 출력하는 get_id_num() 메서드를 추가하세요.**

- 생성자 메서드에서 학번 생성시마다 위에 추가한 total_id_count 변수의 값을 증가하도록 합니다.
- get_id_num으로 현재까지 생성된 학번 개수를 return하도록 합니다.
- get_id_num은 메인퀘스트 (1) 풀이과정에서 학습한 클래스 메서드개념을 적용해서 만들겠습니다.

In [ ]:
class Aiffel:
    # 생성된 학번의 총 개수
    total_id_count = 0  # 학번 생성시 마다 +1

    def __init__(self, name, admission_year="2023", term=29, course_type="코어"):
        self.name = name  # 학생의 이름
        self.admission_year = admission_year  # 입학 연도
        self.term = term  # 기수
        self.course_type = course_type  # 과정 종류
        self.student_id = self.generate_student_id()  # 학번 생성 메서드 호출
        Aiffel.total_id_count += 1  # 학번이 생성될 때마다 카운트 증가

    def generate_student_id(self):
        year = self.admission_year[-2:]  # 입학 연도의 마지막 두 자리
        course_type_num = '2' if self.course_type == "코어" else '1'  # 과정 종류에 따른 숫자 할당
        student_number = str(Aiffel.total_id_count + 1).zfill(2)  # 학번의 순서를 나타내는 두 자리 숫자
        student_id = f"{year}{str(self.term).zfill(2)}{course_type_num}{student_number}"  # 학번 조합
        return student_id  # 생성된 학번 반환

    # Q2. 에서 추가
    @classmethod
    def get_id_num(cls):
        return cls.total_id_count

# 코어 명단 dict
core_members =  {'강영현': 0, '김경민': 0, '김민기': 0, '김승순': 0, '김양희': 0, '김영신': 0,
                 '오우진': 0, '윤혜윤': 0, '이상원': 0, '이선재': 0, '이슬': 0, '이승환': 0, '전민규': 0,
                 '조보겸': 0, '조수민': 0, '최강훈': 0, '한현종': 0, '홍채림': 0}

# 코어 명단을 바탕으로 Aiffel 인스턴스 생성
members_instances = {} # 코어 명단 dict를 바탕으로 Aiffel 클래스의 인스턴스를 생성용 dict

# 각 학생의 이름을 사용하여 Aiffel 클래스의 인스턴스를 생성
# Aiffel 클래스의 생성자에 정의된 기본값(연도, 기수, 과정 종류) 적용
for name in core_members.keys():
    members_instances[name] = Aiffel(name)

# 생성된 인스턴스(그루)의 학번 확인
for name, instance in members_instances.items():
    print(f"이름: {name}, 학번: {instance.student_id}")

# 학번 개수 출력
print(f"생성된 학번의 총 개수: {Aiffel.get_id_num()}")

이름: 강영현, 학번: 2329201
이름: 김경민, 학번: 2329202
이름: 김민기, 학번: 2329203
이름: 김승순, 학번: 2329204
이름: 김양희, 학번: 2329205
이름: 김영신, 학번: 2329206
이름: 오우진, 학번: 2329207
이름: 윤혜윤, 학번: 2329208
이름: 이상원, 학번: 2329209
이름: 이선재, 학번: 2329210
이름: 이슬, 학번: 2329211
이름: 이승환, 학번: 2329212
이름: 전민규, 학번: 2329213
이름: 조보겸, 학번: 2329214
이름: 조수민, 학번: 2329215
이름: 최강훈, 학번: 2329216
이름: 한현종, 학번: 2329217
이름: 홍채림, 학번: 2329218
생성된 학번의 총 개수: 18

### **Q3. Aiffel 클래스에 퀘스트 점수 입력을 위한 score 메서드를 추가하세요. 점수는 +1점 부터 +3점까지만 가능합니다.**

- socre 메서드를 추가합니다.
- 이 메서드에는 점수가 1~3점 사이를 추가할 수 있습니다.
- 점수는 메서드에 인자로 입력받고, 입력받은 점수가 1~3사이인지 검증합니다.
- 검증을 통과한 경우만 score 인자에 추가합니다.
- 예외에 대해 경고문구를 출력합니다.

In [ ]:
class Aiffel:
    # 생성된 학번의 총 개수
    total_id_count = 0  # 학번 생성시 마다 +1

    def __init__(self, name, admission_year="2023", term=29, course_type="코어"):
        self.name = name  # 학생의 이름
        self.admission_year = admission_year  # 입학 연도
        self.term = term  # 기수
        self.course_type = course_type  # 과정 종류
        self.student_id = self.generate_student_id()  # 학번 생성 메서드 호출
        # Q3.에서 추가
        self.score_points = 0  # 초기 점수는 0점으로 설정
        Aiffel.total_id_count += 1  # 학번이 생성될 때마다 카운트 증가

    def generate_student_id(self):
        year = self.admission_year[-2:]  # 입학 연도의 마지막 두 자리
        course_type_num = '2' if self.course_type == "코어" else '1'  # 과정 종류에 따른 숫자 할당
        student_number = str(Aiffel.total_id_count + 1).zfill(2)  # 학번의 순서를 나타내는 두 자리 숫자
        student_id = f"{year}{str(self.term).zfill(2)}{course_type_num}{student_number}"  # 학번 조합
        return student_id  # 생성된 학번 반환

    # Q2. 에서 추가
    @classmethod
    def get_id_num(cls):
        return cls.total_id_count

    # Q3. 에서 추가
    def score(self, points):
        if points in [1, 2, 3]:
            self.score_points += points # 조건에 해당할 경우 점수 추가
        else:
            print("점수는 1점, 2점, 3점 중 1개만 입력 가능합니다.")


# 코어 명단 dict
core_members =  {'강영현': 0, '김경민': 0, '김민기': 0, '김승순': 0, '김양희': 0, '김영신': 0,
                 '오우진': 0, '윤혜윤': 0, '이상원': 0, '이선재': 0, '이슬': 0, '이승환': 0, '전민규': 0,
                 '조보겸': 0, '조수민': 0, '최강훈': 0, '한현종': 0, '홍채림': 0}

# 코어 명단을 바탕으로 Aiffel 인스턴스 생성
members_instances = {} # 코어 명단 dict를 바탕으로 Aiffel 클래스의 인스턴스를 생성용 dict

# 각 학생의 이름을 사용하여 Aiffel 클래스의 인스턴스를 생성
# Aiffel 클래스의 생성자에 정의된 기본값(연도, 기수, 과정 종류) 적용
for name in core_members.keys():
    members_instances[name] = Aiffel(name)

# 테스트: '강영현' 그루에게 2점을 추가
members_instances['강영현'].score(2)

# 결과 확인
print(members_instances['강영현'].score_points)

2

## **Q4. Aiffel 클래스에 퀘스트 점수 차감을 위한 penalty 메서드를 추가하세요. penalty로 인한 잔여 점수는 음수가 가능합니다.**

- 점수를 차감하는 penalty 메서드를 추가합니다.
- 차감할 점수를 메서드와 함께 입력받아서, 인스턴스에 저장된 점수에서 차감하는 식으로 구성되어야 합니다.
- 차감 후 점수는 음수도 가능하므로 별도로 예외처리는 하지 않아도 될것 같습니다.
- 또한 1회에 차감  가능한 점수에 대한 언급도 없었으므로 제한이 없는것으로 설정하겠습니다.

In [ ]:
class Aiffel:
    # 생성된 학번의 총 개수
    total_id_count = 0  # 학번 생성시 마다 +1

    def __init__(self, name, admission_year="2023", term=29, course_type="코어"):
        self.name = name  # 학생의 이름
        self.admission_year = admission_year  # 입학 연도
        self.term = term  # 기수
        self.course_type = course_type  # 과정 종류
        self.student_id = self.generate_student_id()  # 학번 생성 메서드 호출
        # Q3.에서 추가
        self.score_points = 0  # 초기 점수는 0점으로 설정
        Aiffel.total_id_count += 1  # 학번이 생성될 때마다 카운트 증가

    def generate_student_id(self):
        year = self.admission_year[-2:]  # 입학 연도의 마지막 두 자리
        course_type_num = '2' if self.course_type == "코어" else '1'  # 과정 종류에 따른 숫자 할당
        student_number = str(Aiffel.total_id_count + 1).zfill(2)  # 학번의 순서를 나타내는 두 자리 숫자
        student_id = f"{year}{str(self.term).zfill(2)}{course_type_num}{student_number}"  # 학번 조합
        return student_id  # 생성된 학번 반환

    # Q2. 에서 추가
    @classmethod
    def get_id_num(cls):
        return cls.total_id_count

    # Q3. 에서 추가
    def score(self, points):
        if points in [1, 2, 3]:
            self.score_points += points # 조건에 해당할 경우 점수 추가
        else:
            print("점수는 1점, 2점, 3점 중 1개만 입력 가능합니다.")

    # Q4. 에서 추가
    def penalty(self, points):
        self.score_points -= points # 입력받은 점수를 차감 (대상은 인스턴스를 직접 설정할 것이기 때문에 불필요)


# 코어 명단 dict
core_members =  {'강영현': 0, '김경민': 0, '김민기': 0, '김승순': 0, '김양희': 0, '김영신': 0,
                 '오우진': 0, '윤혜윤': 0, '이상원': 0, '이선재': 0, '이슬': 0, '이승환': 0, '전민규': 0,
                 '조보겸': 0, '조수민': 0, '최강훈': 0, '한현종': 0, '홍채림': 0}

# 코어 명단을 바탕으로 Aiffel 인스턴스 생성
members_instances = {} # 코어 명단 dict를 바탕으로 Aiffel 클래스의 인스턴스를 생성용 dict

# 각 학생의 이름을 사용하여 Aiffel 클래스의 인스턴스를 생성
# Aiffel 클래스의 생성자에 정의된 기본값(연도, 기수, 과정 종류) 적용
for name in core_members.keys():
    members_instances[name] = Aiffel(name)

# 테스트: '강영현' 그루에게 2점을 추가
members_instances['강영현'].score(2)

# 테스트: '강영현' 그루에게 1점을 차감
members_instances['강영현'].penalty(1) # 1점이 되어야 함

# 결과 확인
print(members_instances['강영현'].score_points)

1

In [ ]:
# 음수도 나오는지 테스트
# 테스트: '강영현' 그루에게 1점을 차감
members_instances['강영현'].penalty(3) # 1점이 되어야 함

# 결과 확인
print(members_instances['강영현'].score_points)

-2

## **Q5. Aiffel 인스턴스에 저장된 정보를 출력하는 display_info() 메서드를 추가하세요. 해당 메서드를 호출하면 이름, 학번, 과정종류, 퀘스트 점수 총점, 퀘스트 입력 총점, 퀘스트 penalty 총합이 새로운 코어명단(csv파일)로 출력되어야합니다.**

- 문제조건에 따른 출력이 필요한 정보는 아래와 같습니다.
    - 이름, 학번, 과정종류, 퀘스트 점수 총점, 퀘스트 입력총점, 퀘스트 penalty총점
- 이제부터는 생성한 그루정보가 클래스내에 저장이 되어야 할것 같습니다.
- 저장된 각 그루의 인스턴스 정보에 대해서 score와 penalty가 적용되면, 그 값들이 누적하여 저장되어 있다가 출력되어야 합니다.

In [ ]:
import pandas as pd # csv 형태의 데이터 출력용

class Aiffel:
    total_id_count = 0  # 생성된 학번의 총 개수
    instances = {}  # 생성된 Aiffel 인스턴스 목록을 클래스 레벨에서 관리
    members_instances = {} # 코어 명단 dict를 바탕으로 Aiffel 클래스의 인스턴스를 생성용 dict

    def __init__(self, name, admission_year="2023", term=29, course_type="코어"):
        self.name = name  # 학생의 이름
        self.admission_year = admission_year  # 입학 연도
        self.term = term  # 기수
        self.course_type = course_type  # 과정 종류
        self.student_id = self.generate_student_id()  # 학번 생성 메서드 호출
        self.score_points = 0  # 개별 그루의 퀘스트 점수
        self.penalty_points = 0  # 개별 그루의 퀘스트 penalty
        Aiffel.instances[name] = self  # 생성된 인스턴스를 이름을 key로 딕셔너리에 추가
        Aiffel.total_id_count += 1  # 학번 생성시마다 총 학번 개수 증가

    def generate_student_id(self):
        year = self.admission_year[-2:]  # 입학 연도의 마지막 두 자리
        course_type_num = '2' if self.course_type == "코어" else '1'  # 과정 종류에 따른 숫자 할당
        student_number = str(Aiffel.total_id_count + 1).zfill(2)  # 학번의 순서를 나타내는 두 자리 숫자
        student_id = f"{year}{str(self.term).zfill(2)}{course_type_num}{student_number}"  # 학번 조합
        return student_id  # 생성된 학번 반환

    @classmethod
    def get_id_num(cls):
        return cls.total_id_count

    # Q3. 에서 추가
    def score(self, points):
        if points in [1, 2, 3]:
            self.score_points += points  # 조건에 해당할 경우 점수 추가
        else:
            print("점수는 1점, 2점, 3점 중 1개만 입력 가능합니다.")

    # Q4. 에서 추가
    def penalty(self, points):
        self.penalty_points -= points  # 입력받은 점수를 차감

    # Q5. 에서 추가
    @classmethod
    def display_info(cls):
        data = {
            "이름": [],
            "학번": [],
            "과정 종류": [],
            "퀘스트 점수 총점": [],
            "퀘스트 입력 총점": [],
            "퀘스트 penalty 총합": []
        }

        # 클래스 내부에서 instances 변수에 접근
        for name in cls.instances.keys():
            student = cls.instances[name]
            data["이름"].append(student.name)
            data["학번"].append(student.student_id)
            data["과정 종류"].append(student.course_type)
            data["퀘스트 점수 총점"].append(student.score_points + student.penalty_points)
            data["퀘스트 입력 총점"].append(student.score_points)
            data["퀘스트 penalty 총합"].append(student.penalty_points)

        df = pd.DataFrame(data)
        display(df)

# 코어 명단 dict
core_members =  {'강영현': 0, '김경민': 0, '김민기': 0, '김승순': 0, '김양희': 0, '김영신': 0,
                 '오우진': 0, '윤혜윤': 0, '이상원': 0, '이선재': 0, '이슬': 0, '이승환': 0, '전민규': 0,
                 '조보겸': 0, '조수민': 0, '최강훈': 0, '한현종': 0, '홍채림': 0}

# 코어 명단을 바탕으로 Aiffel 인스턴스 생성

# 각 학생의 이름을 사용하여 Aiffel 클래스의 인스턴스를 생성
# Aiffel 클래스의 생성자에 정의된 기본값(연도, 기수, 과정 종류) 적용
for name in core_members.keys():
    members_instances[name] = Aiffel(name)

# 학생 정보 조회
Aiffel.display_info()

     이름       학번 과정 종류  퀘스트 점수 총점  퀘스트 입력 총점  퀘스트 penalty 총합
0   강영현  2329201    코어          0          0               0
1   김경민  2329202    코어          0          0               0
2   김민기  2329203    코어          0          0               0
3   김승순  2329204    코어          0          0               0
4   김양희  2329205    코어          0          0               0
5   김영신  2329206    코어          0          0               0
6   오우진  2329207    코어          0          0               0
7   윤혜윤  2329208    코어          0          0               0
8   이상원  2329209    코어          0          0               0
9   이선재  2329210    코어          0          0               0
10   이슬  2329211    코어          0          0               0
11  이승환  2329212    코어          0          0               0
12  전민규  2329213    코어          0          0               0
13  조보겸  2329214    코어          0          0               0
14  조수민  2329215    코어          0          0               0
15  최강훈  2329216    코어          0          0               0
16  한현종  2329217    코어          0          0               0
17  홍채림  2329218    코어          0          0               0

In [ ]:
# 결과 테스트

# 김승순 학생에게 점수 3점 부여
Aiffel.instances["김승순"].score(3)

# 김승순 학생에게 페널티 6점 부여
Aiffel.instances["김승순"].penalty(6)

# 결과 출력
Aiffel.display_info()

     이름       학번 과정 종류  퀘스트 점수 총점  퀘스트 입력 총점  퀘스트 penalty 총합
0   강영현  2329201    코어          0          0               0
1   김경민  2329202    코어          0          0               0
2   김민기  2329203    코어          0          0               0
3   김승순  2329204    코어         -3          3              -6
4   김양희  2329205    코어          0          0               0
5   김영신  2329206    코어          0          0               0
6   오우진  2329207    코어          0          0               0
7   윤혜윤  2329208    코어          0          0               0
8   이상원  2329209    코어          0          0               0
9   이선재  2329210    코어          0          0               0
10   이슬  2329211    코어          0          0               0
11  이승환  2329212    코어          0          0               0
12  전민규  2329213    코어          0          0               0
13  조보겸  2329214    코어          0          0               0
14  조수민  2329215    코어          0          0               0
15  최강훈  2329216    코어          0          0               0
16  한현종  2329217    코어          0          0               0
17  홍채림  2329218    코어          0          0               0

## **Q6. 중도포기자 관리를 위해 그루정보를 삭제하는 메서드를 추가해보세요. 해당 메서드를 호출하면 명단이 갱신되어야 합니다. 현재 명단에서 김경민, 김영신 님을 삭제한 후 갱신된 명단을 출력하세요.**

- 기능 구현을 위해 remove_member 라는 클래스 메서드를 생성해야 합니다.
- instances 내에 저장된 학생정보를 가지고 접근해서 특정 정보만을 삭제하도록 합니다.
- 삭제할 정보가 없는 경우 오류메시지가 뜨도록 했습니다.

In [ ]:
import pandas as pd # csv 형태의 데이터 출력용

class Aiffel:
    total_id_count = 0  # 생성된 학번의 총 개수
    instances = {}  # 생성된 Aiffel 인스턴스 목록을 클래스 레벨에서 관리
    members_instances = {} # 코어 명단 dict를 바탕으로 Aiffel 클래스의 인스턴스를 생성용 dict

    def __init__(self, name, admission_year="2023", term=29, course_type="코어"):
        self.name = name  # 학생의 이름
        self.admission_year = admission_year  # 입학 연도
        self.term = term  # 기수
        self.course_type = course_type  # 과정 종류
        self.student_id = self.generate_student_id()  # 학번 생성 메서드 호출
        self.score_points = 0  # 개별 그루의 퀘스트 점수
        self.penalty_points = 0  # 개별 그루의 퀘스트 penalty
        Aiffel.instances[name] = self  # 생성된 인스턴스를 이름을 key로 딕셔너리에 추가
        Aiffel.total_id_count += 1  # 학번 생성시마다 총 학번 개수 증가

    def generate_student_id(self):
        year = self.admission_year[-2:]  # 입학 연도의 마지막 두 자리
        course_type_num = '2' if self.course_type == "코어" else '1'  # 과정 종류에 따른 숫자 할당
        student_number = str(Aiffel.total_id_count + 1).zfill(2)  # 학번의 순서를 나타내는 두 자리 숫자
        student_id = f"{year}{str(self.term).zfill(2)}{course_type_num}{student_number}"  # 학번 조합
        return student_id  # 생성된 학번 반환

    @classmethod
    def get_id_num(cls):
        return cls.total_id_count

    # Q3. 에서 추가
    def score(self, points):
        if points in [1, 2, 3]:
            self.score_points += points  # 조건에 해당할 경우 점수 추가
        else:
            print("점수는 1점, 2점, 3점 중 1개만 입력 가능합니다.")

    # Q4. 에서 추가
    def penalty(self, points):
        self.penalty_points -= points  # 입력받은 점수를 차감

    # Q5. 에서 추가
    @classmethod
    def display_info(cls):
        data = {
            "이름": [],
            "학번": [],
            "과정 종류": [],
            "퀘스트 점수 총점": [],
            "퀘스트 입력 총점": [],
            "퀘스트 penalty 총합": []
        }

        # 클래스 내부에서 instances 변수에 접근
        for name in cls.instances.keys():
            student = cls.instances[name]
            data["이름"].append(student.name)
            data["학번"].append(student.student_id)
            data["과정 종류"].append(student.course_type)
            data["퀘스트 점수 총점"].append(student.score_points + student.penalty_points)
            data["퀘스트 입력 총점"].append(student.score_points)
            data["퀘스트 penalty 총합"].append(student.penalty_points)

        df = pd.DataFrame(data)
        display(df)

    # Q6. 중도포기자 관리를 위한 메서드 추가 - 명단 삭제
    @classmethod
    def remove_member(cls, name):
        if name in cls.instances:
            del cls.instances[name]  # 해당 그루 정보 삭제
            print(f"{name} 님의 정보가 삭제되었습니다.")
        else:
            print(f"{name} 님은 명단에 존재하지 않습니다.")


# 클래스내에 그루 정보 생성 및 저장
# 코어 명단 dict
core_members =  {'강영현': 0, '김경민': 0, '김민기': 0, '김승순': 0, '김양희': 0, '김영신': 0,
                 '오우진': 0, '윤혜윤': 0, '이상원': 0, '이선재': 0, '이슬': 0, '이승환': 0, '전민규': 0,
                 '조보겸': 0, '조수민': 0, '최강훈': 0, '한현종': 0, '홍채림': 0}

# 코어 명단을 바탕으로 Aiffel 인스턴스 생성

# 각 학생의 이름을 사용하여 Aiffel 클래스의 인스턴스를 생성
# Aiffel 클래스의 생성자에 정의된 기본값(연도, 기수, 과정 종류) 적용
for name in core_members.keys():
    members_instances[name] = Aiffel(name)

# 학생 정보 조회
Aiffel.display_info()

# remove_member테스트
# 김경민과 김영신을 삭제
Aiffel.remove_member("김경민")
Aiffel.remove_member("김영신")

# 갱신된 명단 출력
Aiffel.display_info()

# 다시한번 삭제 시도
Aiffel.remove_member("김영신")

     이름       학번 과정 종류  퀘스트 점수 총점  퀘스트 입력 총점  퀘스트 penalty 총합
0   강영현  2329201    코어          0          0               0
1   김경민  2329202    코어          0          0               0
2   김민기  2329203    코어          0          0               0
3   김승순  2329204    코어          0          0               0
4   김양희  2329205    코어          0          0               0
5   김영신  2329206    코어          0          0               0
6   오우진  2329207    코어          0          0               0
7   윤혜윤  2329208    코어          0          0               0
8   이상원  2329209    코어          0          0               0
9   이선재  2329210    코어          0          0               0
10   이슬  2329211    코어          0          0               0
11  이승환  2329212    코어          0          0               0
12  전민규  2329213    코어          0          0               0
13  조보겸  2329214    코어          0          0               0
14  조수민  2329215    코어          0          0               0
15  최강훈  2329216    코어          0          0               0
16  한현종  2329217    코어          0          0               0
17  홍채림  2329218    코어          0          0               0

김경민 님의 정보가 삭제되었습니다.
김영신 님의 정보가 삭제되었습니다.

     이름       학번 과정 종류  퀘스트 점수 총점  퀘스트 입력 총점  퀘스트 penalty 총합
0   강영현  2329201    코어          0          0               0
1   김민기  2329203    코어          0          0               0
2   김승순  2329204    코어          0          0               0
3   김양희  2329205    코어          0          0               0
4   오우진  2329207    코어          0          0               0
5   윤혜윤  2329208    코어          0          0               0
6   이상원  2329209    코어          0          0               0
7   이선재  2329210    코어          0          0               0
8    이슬  2329211    코어          0          0               0
9   이승환  2329212    코어          0          0               0
10  전민규  2329213    코어          0          0               0
11  조보겸  2329214    코어          0          0               0
12  조수민  2329215    코어          0          0               0
13  최강훈  2329216    코어          0          0               0
14  한현종  2329217    코어          0          0               0
15  홍채림  2329218    코어          0          0               0

김영신 님은 명단에 존재하지 않습니다.

## **Q7. Aiffel 클래스를 상속하여, 그루 명단을 바탕으로 2인, 3인, 4인으로 랜덤 그룹핑을 해주는 메서드가 추가된 Aiffel_Group 클래스를 만들어 보세요. 그룹이름은 총 8개입니다. (상생, 신뢰, 열정, 이끔, 성장, 가치, 공유, 확산)**

- Aiffel 클래스를 상속하며 모든 정보를 다 승계 받아야 합니다.
- 랜덤 그루핑을 위한 메서드가 추가되어야 합니다.
    - create_random_groupe라는 메서드를 추가하겠습니다.
    - 해당 메서드는 전체 그루 인원정보에서 2인, 3인, 4인의 조합을 랜덤으로 하여 8개의 그룹에 랜덤으로 배치합니다.
    - 즉, 그룹에 배치할 인원을 뽑는 것도 랜덤, 어느 그룹에 배치할지도 랜덤이 되어야 합니다.
    - 다만, 배치될 그룹은 8개가 모두 처음부터 생성되어 있어야 합니다.
- 생성된 그룹 정보는 클래스의 변수로 저장해서 관리합니다.

In [ ]:
import random

class Aiffel_Group(Aiffel):
    # 그룹 이름을 미리 정의
    group_names = ["상생", "신뢰", "열정", "이끔", "성장", "가치", "공유", "확산"]
    # 생성된 그룹을 저장할 딕셔너리를 초기화
    groups = {}

    @classmethod
    def create_random_groups(cls):
        # Aiffel 클래스의 인스턴스들(학생들)의 이름을 리스트로 가져오기
        all_students = list(cls.instances.keys())
        # 학생들의 순서를 랜덤으로 섞기
        random.shuffle(all_students)


        # 먼저 8개의 그룹을 생성
        for group_name in cls.group_names:
            cls.groups[group_name] = []



        # 모든 학생을 그룹에 랜덤으로 배치
        while all_students:
            for group_name in cls.group_names:
                if not all_students:
                    break
                # 각 그룹에 2명, 3명 또는 4명의 학생을 랜덤으로 배치
                group_size = random.choice([2, 3, 4])
                # 남은 학생 수가 결정된 그룹 크기보다 작으면, 남은 학생 수를 그룹 크기로 설정
                group_size = min(group_size, len(all_students))

                # 학생들을 그룹에 할당
                cls.groups[group_name].extend(all_students[:group_size])
                all_students = all_students[group_size:]

    @classmethod
    def display_groups(cls):
        # 저장된 모든 그룹과 그 구성원들을 출력
        for group_name, members in cls.groups.items():
            print(f"그룹 이름: {group_name}, 구성원: {', '.join(members)}")

# Aiffel_Group 클래스의 랜덤 그룹 생성 및 출력 메서드를 호출
Aiffel_Group.create_random_groups()
Aiffel_Group.display_groups()

그룹 이름: 상생, 구성원: 한현종, 이상원, 전민규, 김승순
그룹 이름: 신뢰, 구성원: 윤혜윤, 홍채림, 이승환, 김민기
그룹 이름: 열정, 구성원: 강영현, 조보겸, 이슬
그룹 이름: 이끔, 구성원: 이선재, 조수민
그룹 이름: 성장, 구성원: 최강훈, 김양희, 오우진
그룹 이름: 가치, 구성원:
그룹 이름: 공유, 구성원:
그룹 이름: 확산, 구성원:

## **Q8. Aiffel 클래스를 상속하여, 그루 명단을 바탕으로 "힌튼", "응", "하사비스" 세개의 길드로 그루들을 랜덤 그룹핑 해주는 Aiffel_Guild 클래스를 만들어 보세요.**

- Aiffel 클래스를 상속받아서 Aiffel_Guild 클래스를 만들어야 합니다.
    - 상속시 Aiffel 클래스의 모든 정보를 승계 합니다.
- 그루 명단을 그대로 사용해 길드를 구성해야 합니다.
    - 그루핑은 Q7과 마찬가지로 랜덤으로 진행되어야 합니다.
    - 이를 위해 create_random_guilds 라는 메서드를 만들겠습니다.
    - 이 메서드에 문제에 지정된 3개의 길드를 고정으로 만들고, 그루들을 랜덤하게 매핑합니다.
- 생성된 길드는 Aiffel_Guild 클래스에 변수로 저장해서 직접 관리가 가능하도록 구성하겠습니다.
- 추가로 해당 길드 정보를 출력하는 display_guilds라는 클래스 메서드를 하나 더 추가하겠습니다.

In [ ]:
import random

class Aiffel_Guild(Aiffel):
    guild_names = ["힌튼", "응", "하사비스"]
    guilds = {guild_name: [] for guild_name in guild_names} # 길드명을 key로 하는 dict 생성

    @classmethod
    def create_random_guilds(cls):
        # Aiffel 클래스의 인스턴스들(학생들)의 이름을 리스트로 가져오기(전체 그루 명단)
        all_students = list(cls.instances.keys())
        random.shuffle(all_students)  # 학생들의 순서를 랜덤으로 섞기

        # 학생들을 랜덤하게 길드에 배치
        for student in all_students:
            guild_name = random.choice(cls.guild_names)  # 랜덤한 길드 선택
            cls.guilds[guild_name].append(student)  # 해당 길드에 학생 추가


    @classmethod
    def display_guilds(cls): # 저장된 모든 길드와 그 구성원들을 출력하는 메서드
        for guild_name, members in cls.guilds.items():
            print(f"길드 이름: {guild_name}, 구성원: {', '.join(members)}")

# 예시를 위해 Aiffel_Guild 클래스의 랜덤 길드 생성 및 출력 메서드 호출
Aiffel_Guild.create_random_guilds()
Aiffel_Guild.display_guilds()

길드 이름: 힌튼, 구성원: 전민규, 이슬
길드 이름: 응, 구성원: 윤혜윤, 김양희, 오우진, 최강훈, 조수민, 이승환, 김민기, 홍채림, 김승순, 강영현
길드 이름: 하사비스, 구성원: 조보겸, 이상원, 이선재, 한현종

## **Q9. Aiffel_Guild 클래스에 길드별 점수를 입력하고 차감하는 guild_score 메서드를 추가해보세요. guild_score 메서드는 길드 이름과 점수를 인자로 받고 길드별 스코어를 출력합니다. guild_score 메서드ㅏ로 점수가 입력되거나 차감되면, Aiffel 클래스에서 구현된 개별 그루의 score도 소속 길드에서 추가되거나 차감된 점수에 따라 별도로 증감되어야 합니다.**

- ex) 모든 길드의 점수가 현재 0점이고, 김양희, 조수민, 조보겸 그루의 개별 점수가 각각 2,3,1이며, 박영수, 심지안 그루는 힌튼 길드, 박근수 그루는 응 길드 라고 했을 때, 힌튼 길드가 -1점, 응길드가 +1점을 받았다면 길드점수는 힌튼 길드 -1, 응 길드 +1, 하사비스 길드 +0이 되어야 하고 김양희, 조보겸 그루는 각각 1점과 0점, 조수민 그루는 4점이 되어야 합니다.

---

- 문제 요구사항대로 길드 점수 관리를 위한 메서드를 추가해야 합니다.
    - 길드 이름과 점수를 인자로 받아서 작동하도록 합니다.
    - 지정된 길드의 점수를 변경하도록 해야 합니다.
    - 또한, 변경된 점수는 해당 길드에 속한 모든 그루의 개별점수에도 반영되어야 합니다.

In [ ]:
import random

class Aiffel_Guild(Aiffel):
    guild_names = ["힌튼", "응", "하사비스"]
    guilds = {guild_name: [] for guild_name in guild_names} # 길드명을 key로 하는 dict 생성
    guild_scores = {guild_name: 0 for guild_name in guild_names}  # 길드별 점수 초기화

    @classmethod
    def create_random_guilds(cls):
        # Aiffel 클래스의 인스턴스들(학생들)의 이름을 리스트로 가져오기(전체 그루 명단)
        all_students = list(cls.instances.keys())
        random.shuffle(all_students)  # 학생들의 순서를 랜덤으로 섞기

        # 학생들을 랜덤하게 길드에 배치
        for student in all_students:
            guild_name = random.choice(cls.guild_names)  # 랜덤한 길드 선택
            cls.guilds[guild_name].append(student)  # 해당 길드에 학생 추가

    # Q9.에서 추가
    @classmethod
    def guild_score(cls, guild_name, score_change):
        # 지정된 길드의 점수를 변경
        if guild_name in cls.guild_scores:
            cls.guild_scores[guild_name] += score_change

            # 길드에 속한 그루의 점수도 변경
            for student in cls.guilds[guild_name]:
                cls.instances[student].score_points += score_change

    @classmethod
    def display_guilds(cls): # 저장된 모든 길드와 그 구성원들을 출력하는 메서드
        for guild_name, members in cls.guilds.items():
            print(f"길드 이름: {guild_name}, 구성원: {', '.join(members)}")



# 결과 확인

# 길드 생성 및 결과 표시
Aiffel_Guild.create_random_guilds()
Aiffel_Guild.display_guilds()

# 점수 변경 전 정보 표시
Aiffel.display_info()  # Aiffel 클래스의 메서드를 호출

# 길드 점수 변경
Aiffel_Guild.guild_score("힌튼", -1)
Aiffel_Guild.guild_score("응", 1)

# 점수 변경 후 정보 표시
Aiffel.display_info()  # 변경된 점수를 반영하여 정보 재표시

길드 이름: 힌튼, 구성원: 조보겸, 한현종, 전민규, 홍채림
길드 이름: 응, 구성원: 이승환, 최강훈, 김양희, 강영현
길드 이름: 하사비스, 구성원: 이슬, 김민기, 오우진, 조수민, 이선재, 윤혜윤, 이상원, 김승순

     이름       학번 과정 종류  퀘스트 점수 총점  퀘스트 입력 총점  퀘스트 penalty 총합
0   강영현  2329201    코어          0          0               0
1   김민기  2329203    코어          0          0               0
2   김승순  2329204    코어          0          0               0
3   김양희  2329205    코어          0          0               0
4   오우진  2329207    코어          0          0               0
5   윤혜윤  2329208    코어          0          0               0
6   이상원  2329209    코어          0          0               0
7   이선재  2329210    코어          0          0               0
8    이슬  2329211    코어          0          0               0
9   이승환  2329212    코어          0          0               0
10  전민규  2329213    코어          0          0               0
11  조보겸  2329214    코어          0          0               0
12  조수민  2329215    코어          0          0               0
13  최강훈  2329216    코어          0          0               0
14  한현종  2329217    코어          0          0               0
15  홍채림  2329218    코어          0          0               0

     이름       학번 과정 종류  퀘스트 점수 총점  퀘스트 입력 총점  퀘스트 penalty 총합
0   강영현  2329201    코어          1          1               0
1   김민기  2329203    코어          0          0               0
2   김승순  2329204    코어          0          0               0
3   김양희  2329205    코어          1          1               0
4   오우진  2329207    코어          0          0               0
5   윤혜윤  2329208    코어          0          0               0
6   이상원  2329209    코어          0          0               0
7   이선재  2329210    코어          0          0               0
8    이슬  2329211    코어          0          0               0
9   이승환  2329212    코어          1          1               0
10  전민규  2329213    코어         -1         -1               0
11  조보겸  2329214    코어         -1         -1               0
12  조수민  2329215    코어          0          0               0
13  최강훈  2329216    코어          1          1               0
14  한현종  2329217    코어         -1         -1               0
15  홍채림  2329218    코어         -1         -1               0

## **Q 10. Aiffel_Group 클래스에 group2guild_score 메서드를 추가하세요. group2guild_score 메서드는 아래와 같이 작동해야 합니다.**

- 랜덤으로 그룹핑된 그루들이 소속된 그룹의 이름으로 점수를 받게 되면, 각자 소속된 길드의 점수로 연동되어 계산되게 합니다.
- ex) 이선재(Q8에서 응 길드원으로 랜덤 배치되었다 가정), 강영현(Q8에서 힌튼 길드원으로 랜덤 배치되었다 가정), 한현종(Q8에서 하사비스 길드원으로 랜덤 배치되었다 가정) 3명이 Q7에서 "상상" 그룹으로 그룹핑 되었을 때,상생 그룹이 +2점을 받으면 "응"길드와 "힌튼길드"와 "하사비스" 길드의 스코어는 각각 +2점이 되어야 합니다.

---

- 문제 요구사항에 따라 group2guild_score 메서드를 추가해야 합니다.
    - 그룹 이름과 점수를 인자로 받아 작동합니다.
    - 지정된 그룹에 속한 멤버들의 길드가 무엇인지 확인하는 기능이 있어야 합니다.
    - 해당 멤버들이 속한 길드의 점수를 변경합니다.
        - 만약 한 그룹에 여러 길드의 멤버가 속해있을 수 있으니 이를 고려합니다.
        - 이 경우 모든 관련 길드의 점수를 변경하도록 하면 될 것 같습니다.

In [ ]:
class Aiffel_Group(Aiffel):
    # 그룹 이름을 미리 정의
    group_names = ["상생", "신뢰", "열정", "이끔", "성장", "가치", "공유", "확산"]
    # 생성된 그룹을 저장할 딕셔너리를 초기화
    groups = {}

    @classmethod
    def create_random_groups(cls):
        # Aiffel 클래스의 인스턴스들(학생들)의 이름을 리스트로 가져오기
        all_students = list(cls.instances.keys())
        # 학생들의 순서를 랜덤으로 섞기
        random.shuffle(all_students)

        # 정의된 그룹 이름만큼 반복하여 각 그룹에 학생들을 할당
        for group_name in cls.group_names:
            # 그룹의 구성원 수를 2, 3, 4 중 랜덤으로 결정
            group_size = random.choice([2, 3, 4])
            if group_size > len(all_students):
                group_size = len(all_students) # 만약 남은 학생 수가 결정된 그룹 크기보다 작으면 남은 학생 수를 그룹 크기로 설정

            # 결정된 그룹 크기만큼 학생을 그룹에 할당
            group_members = all_students[:group_size]
            # 할당된 학생들을 전체 학생 목록에서 제거
            all_students = all_students[group_size:]

            # 그룹명과 구성원을 그룹 딕셔너리에 추가
            cls.groups[group_name] = group_members

            # 모든 학생이 그룹에 할당되면 반복을 중단
            if not all_students:
                break

    @classmethod
    def display_groups(cls):
        # 저장된 모든 그룹과 그 구성원들을 출력
        for group_name, members in cls.groups.items():
            print(f"그룹 이름: {group_name}, 구성원: {', '.join(members)}")

    # Q 10. 에서 추가
    @classmethod
    def group2guild_score(cls, group_name, score):
        """
        지정된 그룹에 속한 멤버의 길드를 확인하고 점수를 변경
        지정된 그룹에 점수가 추가되면 해당 그룹에 속한 멤버들의 길드에도 동일한 점수가 추가
        """
        # 지정된 그룹 이름이 cls.groups에 존재하는지 확인
        if group_name in cls.groups:
            # 그룹에 속한 모든 멤버(학생)를 순회하며 확인
            for student in cls.groups[group_name]:
                # 각 학생이 속한 길드를 찾기 위해 모든 길드를 순회하며 확인
                for guild_name, members in Aiffel_Guild.guilds.items():
                    # 해당 학생이 길드의 멤버 목록에 있는지에 따라 점수 추가
                    if student in members:
                        # 학생이 속한 길드에 점수를 추가
                        Aiffel_Guild.guild_score(guild_name, score)
                        """
                        그루 1명 = 소속 길드 1개 -> 소속 길드를 찾았으므로 점수를 적용하고 종료
                        """
                        break

    @classmethod
    def display_guilds(cls): # 저장된 모든 길드와 그 구성원들을 출력하는 메서드
        for guild_name, members in cls.guilds.items():
            print(f"길드 이름: {guild_name}, 구성원: {', '.join(members)}")



# 결과 확인

# 길드 생성 및 초기 길드 정보 표시
Aiffel_Guild.create_random_guilds()
Aiffel_Guild.display_guilds()

# 랜덤 그룹 생성 및 초기 그룹 정보 표시
Aiffel_Group.create_random_groups()
Aiffel_Group.display_groups()

# 초기 그루 점수 정보 표시
Aiffel.display_info()

# '상상' 그룹에 +2 점수 부여
Aiffel_Group.group2guild_score("상생", 2)

# 점수 부여 후 길드 및 그루 점수 정보 재표시
Aiffel.display_info()

길드 이름: 힌튼, 구성원: 조보겸, 한현종, 전민규, 홍채림, 김양희, 김민기, 이상원, 조수민
길드 이름: 응, 구성원: 이승환, 최강훈, 김양희, 강영현, 김승순, 이승환, 윤혜윤, 전민규, 이슬, 홍채림, 오우진, 조보겸, 강영현
길드 이름: 하사비스, 구성원: 이슬, 김민기, 오우진, 조수민, 이선재, 윤혜윤, 이상원, 김승순, 최강훈, 이선재, 한현종
그룹 이름: 상생, 구성원: 한현종, 이상원, 이승환, 조수민
그룹 이름: 신뢰, 구성원: 홍채림, 오우진, 이선재, 김양희
그룹 이름: 열정, 구성원: 윤혜윤, 김승순, 이슬
그룹 이름: 이끔, 구성원: 강영현, 전민규
그룹 이름: 성장, 구성원: 조보겸, 최강훈, 김민기

     이름       학번 과정 종류  퀘스트 점수 총점  퀘스트 입력 총점  퀘스트 penalty 총합
0   강영현  2329201    코어          1          1               0
1   김민기  2329203    코어          0          0               0
2   김승순  2329204    코어          0          0               0
3   김양희  2329205    코어          1          1               0
4   오우진  2329207    코어          0          0               0
5   윤혜윤  2329208    코어          0          0               0
6   이상원  2329209    코어          0          0               0
7   이선재  2329210    코어          0          0               0
8    이슬  2329211    코어          0          0               0
9   이승환  2329212    코어          1          1               0
10  전민규  2329213    코어         -1         -1               0
11  조보겸  2329214    코어         -1         -1               0
12  조수민  2329215    코어          0          0               0
13  최강훈  2329216    코어          1          1               0
14  한현종  2329217    코어         -1         -1               0
15  홍채림  2329218    코어         -1         -1               0

     이름       학번 과정 종류  퀘스트 점수 총점  퀘스트 입력 총점  퀘스트 penalty 총합
0   강영현  2329201    코어          5          5               0
1   김민기  2329203    코어          6          6               0
2   김승순  2329204    코어          2          2               0
3   김양희  2329205    코어          9          9               0
4   오우진  2329207    코어          2          2               0
5   윤혜윤  2329208    코어          2          2               0
6   이상원  2329209    코어          6          6               0
7   이선재  2329210    코어          0          0               0
8    이슬  2329211    코어          2          2               0
9   이승환  2329212    코어          5          5               0
10  전민규  2329213    코어          7          7               0
11  조보겸  2329214    코어          7          7               0
12  조수민  2329215    코어          6          6               0
13  최강훈  2329216    코어          3          3               0
14  한현종  2329217    코어          5          5               0
15  홍채림  2329218    코어          7          7               0

- 기능 구현을 하긴 했는데, 더해지는 로직이 잘못된것 같습니다. 필요이상으로 많은 덧셈이 이뤄집니다.
- 차후 디버깅을 좀 해봐야겠습니다.

## **11. Aiffel_Group 클래스와 Aiffel_Guild클래스가 Aiffel 클래스의 display_info() 메서드를 아래와 같이 오버라이딩 하도록 합니다.**

- 기존 명단에 길드별 스코어 총합이 보이도록 명단을 출력하도록 display_info()를 오버라이딩 합니다.
---

- 문제 풀이를 위해 아래의 작업을 진행해야 합니다.
    - Aiffel_Group 클래스 오버라이딩: display_info() 메서드를 오버라이딩하여 각 그룹의 정보와 그룹 멤버들의 길드 스코어 총합을 표시
    - Aiffel_Guild 클래스 오버라이딩: display_info() 메서드를 오버라이딩하여 각 길드의 정보와 길드별 스코어 총합을 표시

In [ ]:
"""
Aiffel_Group 의 정보 오버라이딩
"""
class Aiffel_Group(Aiffel):
    # 그룹 이름을 미리 정의
    group_names = ["상생", "신뢰", "열정", "이끔", "성장", "가치", "공유", "확산"]
    # 생성된 그룹을 저장할 딕셔너리를 초기화
    groups = {}

    @classmethod
    def create_random_groups(cls):
        # Aiffel 클래스의 인스턴스들(학생들)의 이름을 리스트로 가져오기
        all_students = list(cls.instances.keys())
        # 학생들의 순서를 랜덤으로 섞기
        random.shuffle(all_students)

        # 정의된 그룹 이름만큼 반복하여 각 그룹에 학생들을 할당
        for group_name in cls.group_names:
            # 그룹의 구성원 수를 2, 3, 4 중 랜덤으로 결정
            group_size = random.choice([2, 3, 4])
            if group_size > len(all_students):
                group_size = len(all_students) # 만약 남은 학생 수가 결정된 그룹 크기보다 작으면 남은 학생 수를 그룹 크기로 설정

            # 결정된 그룹 크기만큼 학생을 그룹에 할당
            group_members = all_students[:group_size]
            # 할당된 학생들을 전체 학생 목록에서 제거
            all_students = all_students[group_size:]

            # 그룹명과 구성원을 그룹 딕셔너리에 추가
            cls.groups[group_name] = group_members

            # 모든 학생이 그룹에 할당되면 반복을 중단
            if not all_students:
                break

    @classmethod
    def display_groups(cls):
        # 저장된 모든 그룹과 그 구성원들을 출력
        for group_name, members in cls.groups.items():
            print(f"그룹 이름: {group_name}, 구성원: {', '.join(members)}")

    # Q 10. 에서 추가
    @classmethod
    def group2guild_score(cls, group_name, score):
        """
        지정된 그룹에 속한 멤버의 길드를 확인하고 점수를 변경
        지정된 그룹에 점수가 추가되면 해당 그룹에 속한 멤버들의 길드에도 동일한 점수가 추가
        """
        # 지정된 그룹 이름이 cls.groups에 존재하는지 확인
        if group_name in cls.groups:
            # 그룹에 속한 모든 멤버(학생)를 순회하며 확인
            for student in cls.groups[group_name]:
                # 각 학생이 속한 길드를 찾기 위해 모든 길드를 순회하며 확인
                for guild_name, members in Aiffel_Guild.guilds.items():
                    # 해당 학생이 길드의 멤버 목록에 있는지에 따라 점수 추가
                    if student in members:
                        # 학생이 속한 길드에 점수를 추가
                        Aiffel_Guild.guild_score(guild_name, score)
                        """
                        그루 1명 = 소속 길드 1개 -> 소속 길드를 찾았으므로 점수를 적용하고 종료
                        """
                        break

    @classmethod
    def display_guilds(cls): # 저장된 모든 길드와 그 구성원들을 출력하는 메서드
        for guild_name, members in cls.guilds.items():
            print(f"길드 이름: {guild_name}, 구성원: {', '.join(members)}")

    # Q.11에 추가 : 오버라이딩
    @classmethod
    def display_info(cls):
        # 각 그룹과 그룹 멤버들의 길드 스코어 총합을 표시
        for group_name, members in cls.groups.items():
            print(f"그룹: {group_name}")
            for member in members:
                # 멤버의 길드 찾기
                guild_name = next((g for g, m in Aiffel_Guild.guilds.items() if member in m), None)
                # 멤버의 길드 스코어 총합 표시
                if guild_name:
                    score = Aiffel_Guild.guild_scores[guild_name]
                    print(f"  - {member} (길드: {guild_name}, 길드 스코어: {score})")


"""
Aiffel_Guild의 클래스 오버라딩
"""
class Aiffel_Guild(Aiffel):
    guild_names = ["힌튼", "응", "하사비스"]
    guilds = {guild_name: [] for guild_name in guild_names} # 길드명을 key로 하는 dict 생성
    guild_scores = {guild_name: 0 for guild_name in guild_names}  # 길드별 점수 초기화

    @classmethod
    def create_random_guilds(cls):
        # Aiffel 클래스의 인스턴스들(학생들)의 이름을 리스트로 가져오기(전체 그루 명단)
        all_students = list(cls.instances.keys())
        random.shuffle(all_students)  # 학생들의 순서를 랜덤으로 섞기

        # 학생들을 랜덤하게 길드에 배치
        for student in all_students:
            guild_name = random.choice(cls.guild_names)  # 랜덤한 길드 선택
            cls.guilds[guild_name].append(student)  # 해당 길드에 학생 추가

    # Q9.에서 추가
    @classmethod
    def guild_score(cls, guild_name, score_change):
        # 지정된 길드의 점수를 변경
        if guild_name in cls.guild_scores:
            cls.guild_scores[guild_name] += score_change

            # 길드에 속한 그루의 점수도 변경
            for student in cls.guilds[guild_name]:
                cls.instances[student].score_points += score_change

    @classmethod
    def display_guilds(cls): # 저장된 모든 길드와 그 구성원들을 출력하는 메서드
        for guild_name, members in cls.guilds.items():
            print(f"길드 이름: {guild_name}, 구성원: {', '.join(members)}")

    # Q.11에 추가 : 오버라이딩
    @classmethod
    def display_info(cls):
        # 각 길드의 정보와 길드별 스코어 총합을 표시
        for guild_name, score in cls.guild_scores.items():
            print(f"길드: {guild_name}, 길드 스코어 총합: {score}")


# 결과 확인
# 랜덤 길드 및 그룹 생성
Aiffel_Guild.create_random_guilds()
Aiffel_Group.create_random_groups()

# 초기 길드 및 그룹 정보 표시
print("초기 길드 정보:")
Aiffel_Guild.display_info()
print("\n초기 그룹 정보:")
Aiffel_Group.display_info()

# 특정 길드에 점수 부여 (예시로 '힌튼' 길드에 +3 점)
Aiffel_Guild.guild_score("힌튼", 3)

# 점수 변경 후 길드 및 그룹 정보 표시
print("\n점수 변경 후 길드 정보:")
Aiffel_Guild.display_info()
print("\n점수 변경 후 그룹 정보:")
Aiffel_Group.display_info()

초기 길드 정보:
길드: 힌튼, 길드 스코어 총합: 0
길드: 응, 길드 스코어 총합: 0
길드: 하사비스, 길드 스코어 총합: 0

초기 그룹 정보:
그룹: 상생
  - 윤혜윤 (길드: 힌튼, 길드 스코어: 0)
  - 최강훈 (길드: 하사비스, 길드 스코어: 0)
  - 김양희 (길드: 하사비스, 길드 스코어: 0)
  - 김승순 (길드: 하사비스, 길드 스코어: 0)
그룹: 신뢰
  - 이선재 (길드: 응, 길드 스코어: 0)
  - 오우진 (길드: 응, 길드 스코어: 0)
  - 조보겸 (길드: 하사비스, 길드 스코어: 0)
  - 김민기 (길드: 힌튼, 길드 스코어: 0)
그룹: 열정
  - 강영현 (길드: 하사비스, 길드 스코어: 0)
  - 한현종 (길드: 하사비스, 길드 스코어: 0)
  - 홍채림 (길드: 하사비스, 길드 스코어: 0)
  - 이슬 (길드: 응, 길드 스코어: 0)
그룹: 이끔
  - 이상원 (길드: 응, 길드 스코어: 0)
  - 조수민 (길드: 하사비스, 길드 스코어: 0)
  - 전민규 (길드: 응, 길드 스코어: 0)
그룹: 성장
  - 이승환 (길드: 하사비스, 길드 스코어: 0)

점수 변경 후 길드 정보:
길드: 힌튼, 길드 스코어 총합: 3
길드: 응, 길드 스코어 총합: 0
길드: 하사비스, 길드 스코어 총합: 0

점수 변경 후 그룹 정보:
그룹: 상생
  - 윤혜윤 (길드: 힌튼, 길드 스코어: 3)
  - 최강훈 (길드: 하사비스, 길드 스코어: 0)
  - 김양희 (길드: 하사비스, 길드 스코어: 0)
  - 김승순 (길드: 하사비스, 길드 스코어: 0)
그룹: 신뢰
  - 이선재 (길드: 응, 길드 스코어: 0)
  - 오우진 (길드: 응, 길드 스코어: 0)
  - 조보겸 (길드: 하사비스, 길드 스코어: 0)
  - 김민기 (길드: 힌튼, 길드 스코어: 3)
그룹: 열정
  - 강영현 (길드: 하사비스, 길드 스코어: 0)
  - 한현종 (길드: 하사비스, 길드 스코어: 0)
  - 홍채림 (길드: 하사비스, 길드 스코어: 0)
  - 이슬 (길드: 응, 길드 스코어: 0)
그룹: 이끔
  - 이상원 (길드: 응, 길드 스코어: 0)
  - 조수민 (길드: 하사비스, 길드 스코어: 0)
  - 전민규 (길드: 응, 길드 스코어: 0)
그룹: 성장
  - 이승환 (길드: 하사비스, 길드 스코어: 0)

# 회고
---

KEEP
- 개념하나 하나 짚어 가면서 문제 풀이계획 세우고 풀기 시작한건 잘했다고 생각함.
- 구조도 그리고 시작하지 않았으면 더 오래걸렸을 것 같다.

PROBLEM
- 머리속에서 생각은 돌아가는데, 그걸 구현하는 코딩 스킬이 너무 부족한걸 체감했다.
- 실제 방법이나 구성이 생각이 잘 안나서 시행착오를 너무 많이 겪었다.
- 주석을 상세하게 달려고하는건 좋은데 너무 주석 내용을 생각하다 보니 정작 코드를 작성 못했던것 같다.

TRY
- 코딩 테스트같은걸 통해서 문제 풀이를 좀더 연습하고 스킬 키우는 역량을 길러야겠다.